let Dim_Specialty = function() {
    return [
        {
         "Spec_Source": "Manual Add", 
         "Specialty": "Anesthesiology", 
         "specialty_abbr": "Anesthesiology", 
         "Flag_Acute": "Y", 
         "Flag_Ambulatory": null, 
         "Parent_Specialty": 3, 
         "Flag_PrimaryCare": "N", 
         "Specialty_LVL": 3, 
         "Create_Date": "2015-01-21 09.48.44.387", 
         "ID_Specialty": 53
        }, 
        {
         "Spec_Source": "Project Metadata", 
         "Specialty": "Cardiology", 
         "specialty_abbr": "Cardiology", 
         "Flag_Acute": "Y", 
         "Flag_Ambulatory": null, 
         "Parent_Specialty": 5, 
         "Flag_PrimaryCare": "N", 
         "Specialty_LVL": 3, 
         "Create_Date": "2015-01-21 09.48.44.387", 
         "ID_Specialty": 55
        }, 
        {
         "Spec_Source": "Project Metadata", 
         "Specialty": "Dermatology", 
         "specialty_abbr": "Dermatology", 
         "Flag_Acute": "N", 
         "Flag_Ambulatory": null, 
         "Parent_Specialty": 7, 
         "Flag_PrimaryCare": "N", 
         "Specialty_LVL": 3, 
         "Create_Date": "2015-01-21 09.48.44.387", 
         "ID_Specialty": 57
        }, 
        {
         "Spec_Source": "Project Metadata", 
         "Specialty": "Emergency Medicine", 
         "specialty_abbr": "ER", 
         "Flag_Acute": "Y", 
         "Flag_Ambulatory": null, 
         "Parent_Specialty": 8, 
         "Flag_PrimaryCare": "N", 
         "Specialty_LVL": 3, 
         "Create_Date": "2015-01-21 09.48.44.387", 
         "ID_Specialty": 58
        }, 
        {
         "Spec_Source": "Project Metadata", 
         "Specialty": "Endocrinology", 
         "specialty_abbr": "Endocrinology", 
         "Flag_Acute": "N", 
         "Flag_Ambulatory": null, 
         "Parent_Specialty": 9, 
         "Flag_PrimaryCare": "N", 
         "Specialty_LVL": 3, 
         "Create_Date": "2015-01-21 09.48.44.387", 
         "ID_Specialty": 59
        }, 
        {
         "Spec_Source": "Project Metadata", 
         "Specialty": "Family Medicine", 
         "specialty_abbr": "FM", 
         "Flag_Acute": "N", 
         "Flag_Ambulatory": null, 
         "Parent_Specialty": 35, 
         "Flag_PrimaryCare": "Y", 
         "Specialty_LVL": 3, 
         "Create_Date": "2015-01-21 09.48.44.387", 
         "ID_Specialty": 61
        }, 
        {
         "Spec_Source": "Project Metadata", 
         "Specialty": "Gastroenterology", 
         "specialty_abbr": "GI", 
         "Flag_Acute": "Y", 
         "Flag_Ambulatory": null, 
         "Parent_Specialty": 10, 
         "Flag_PrimaryCare": "N", 
         "Specialty_LVL": 3, 
         "Create_Date": "2015-01-21 09.48.44.387", 
         "ID_Specialty": 62
        }, 
        {
         "Spec_Source": "Manual Add", 
         "Specialty": "Hepatology", 
         "specialty_abbr": "Hepatology", 
         "Flag_Acute": "Y", 
         "Flag_Ambulatory": null, 
         "Parent_Specialty": 15, 
         "Flag_PrimaryCare": "N", 
         "Specialty_LVL": 3, 
         "Create_Date": "2015-01-21 09.48.44.387", 
         "ID_Specialty": 67
        }, 
        {
         "Spec_Source": "Project Metadata", 
         "Specialty": "Internal Medicine", 
         "specialty_abbr": "IM", 
         "Flag_Acute": "N", 
         "Flag_Ambulatory": null, 
         "Parent_Specialty": 18, 
         "Flag_PrimaryCare": "Y", 
         "Specialty_LVL": 3, 
         "Create_Date": "2015-01-21 09.48.44.387", 
         "ID_Specialty": 70
        }, 
        {
         "Spec_Source": "Project Metadata", 
         "Specialty": "Nephrology", 
         "specialty_abbr": "Nephrology", 
         "Flag_Acute": "N", 
         "Flag_Ambulatory": null, 
         "Parent_Specialty": 20, 
         "Flag_PrimaryCare": "N", 
         "Specialty_LVL": 3, 
         "Create_Date": "2015-01-21 09.48.44.387", 
         "ID_Specialty": 72
        }, 
        {
         "Spec_Source": "Project Metadata", 
         "Specialty": "Obstetrics and Gynecology", 
         "specialty_abbr": "OBGYN", 
         "Flag_Acute": "Y", 
         "Flag_Ambulatory": null, 
         "Parent_Specialty": 23, 
         "Flag_PrimaryCare": "N", 
         "Specialty_LVL": 3, 
         "Create_Date": "2015-01-21 09.48.44.387", 
         "ID_Specialty": 77
        }, 
        {
         "Spec_Source": "Project Metadata", 
         "Specialty": "Oncology", 
         "specialty_abbr": "Oncology", 
         "Flag_Acute": "Y", 
         "Flag_Ambulatory": null, 
         "Parent_Specialty": 24, 
         "Flag_PrimaryCare": "N", 
         "Specialty_LVL": 3, 
         "Create_Date": "2015-01-21 09.48.44.387", 
         "ID_Specialty": 78
        }, 
        {
         "Spec_Source": "Project Metadata", 
         "Specialty": "Ophthalmology", 
         "specialty_abbr": "Ophthalmology", 
         "Flag_Acute": "N", 
         "Flag_Ambulatory": null, 
         "Parent_Specialty": 25, 
         "Flag_PrimaryCare": "N", 
         "Specialty_LVL": 3, 
         "Create_Date": "2015-01-21 09.48.44.387", 
         "ID_Specialty": 79
        }, 
        {
         "Spec_Source": "Project Metadata", 
         "Specialty": "Orthopedics", 
         "specialty_abbr": "Orthopedics", 
         "Flag_Acute": "Y", 
         "Flag_Ambulatory": null, 
         "Parent_Specialty": 26, 
         "Flag_PrimaryCare": "N", 
         "Specialty_LVL": 3, 
         "Create_Date": "2015-01-21 09.48.44.387", 
         "ID_Specialty": 80
        }, 
        {
         "Spec_Source": "Project Metadata", 
         "Specialty": "Otolaryngology", 
         "specialty_abbr": "Otolaryngology", 
         "Flag_Acute": "N", 
         "Flag_Ambulatory": null, 
         "Parent_Specialty": 27, 
         "Flag_PrimaryCare": "N", 
         "Specialty_LVL": 3, 
         "Create_Date": "2015-01-21 09.48.44.387", 
         "ID_Specialty": 81
        }, 
        {
         "Spec_Source": "Project Metadata", 
         "Specialty": "Pediatrics", 
         "specialty_abbr": "Peds", 
         "Flag_Acute": "N", 
         "Flag_Ambulatory": null, 
         "Parent_Specialty": 28, 
         "Flag_PrimaryCare": "Y", 
         "Specialty_LVL": 3, 
         "Create_Date": "2015-01-21 09.48.44.387", 
         "ID_Specialty": 82
        }, 
        {
         "Spec_Source": "Manual Add", 
         "Specialty": "Physical Medicine and Rehabilitation", 
         "specialty_abbr": "Physical Medicine", 
         "Flag_Acute": "Y", 
         "Flag_Ambulatory": null, 
         "Parent_Specialty": 31, 
         "Flag_PrimaryCare": "N", 
         "Specialty_LVL": 3, 
         "Create_Date": "2015-01-21 09.48.44.387", 
         "ID_Specialty": 85
        }, 
        {
         "Spec_Source": "Project Metadata", 
         "Specialty": "Plastic Surgery", 
         "specialty_abbr": "Plastic Surgery", 
         "Flag_Acute": "N", 
         "Flag_Ambulatory": null, 
         "Parent_Specialty": 32, 
         "Flag_PrimaryCare": "N", 
         "Specialty_LVL": 3, 
         "Create_Date": "2015-01-21 09.48.44.387", 
         "ID_Specialty": 86
        }, 
        {
         "Spec_Source": "Project Metadata", 
         "Specialty": "Podiatry", 
         "specialty_abbr": "Podiatry", 
         "Flag_Acute": "N", 
         "Flag_Ambulatory": null, 
         "Parent_Specialty": 34, 
         "Flag_PrimaryCare": "N", 
         "Specialty_LVL": 3, 
         "Create_Date": "2015-01-21 09.48.44.387", 
         "ID_Specialty": 88
        }, 
        {
         "Spec_Source": "Project Metadata", 
         "Specialty": "Pulmonology", 
         "specialty_abbr": "Pulmonology", 
         "Flag_Acute": "N", 
         "Flag_Ambulatory": null, 
         "Parent_Specialty": 39, 
         "Flag_PrimaryCare": "N", 
         "Specialty_LVL": 3, 
         "Create_Date": "2015-01-21 09.48.44.387", 
         "ID_Specialty": 93
        }, 
        {
         "Spec_Source": "Project Metadata", 
         "Specialty": "Radiology", 
         "specialty_abbr": "Radiology", 
         "Flag_Acute": "Y", 
         "Flag_Ambulatory": null, 
         "Parent_Specialty": 40, 
         "Flag_PrimaryCare": "N", 
         "Specialty_LVL": 3, 
         "Create_Date": "2015-01-21 09.48.44.387", 
         "ID_Specialty": 94
        }, 
        {
         "Spec_Source": "Project Metadata", 
         "Specialty": "Rheumatology", 
         "specialty_abbr": "Rheumatology", 
         "Flag_Acute": "N", 
         "Flag_Ambulatory": null, 
         "Parent_Specialty": 42, 
         "Flag_PrimaryCare": "N", 
         "Specialty_LVL": 3, 
         "Create_Date": "2015-01-21 09.48.44.387", 
         "ID_Specialty": 96
        }, 
        {
         "Spec_Source": "Manual Add", 
         "Specialty": "Surgery", 
         "specialty_abbr": "Surgery", 
         "Flag_Acute": "Y", 
         "Flag_Ambulatory": null, 
         "Parent_Specialty": 45, 
         "Flag_PrimaryCare": "N", 
         "Specialty_LVL": 3, 
         "Create_Date": "2015-01-21 09.48.44.387", 
         "ID_Specialty": 99
        }, 
        {
         "Spec_Source": "Manual Add", 
         "Specialty": "Transplant Medicine", 
         "specialty_abbr": "Transplant Medicine", 
         "Flag_Acute": "Y", 
         "Flag_Ambulatory": null, 
         "Parent_Specialty": 47, 
         "Flag_PrimaryCare": "N", 
         "Specialty_LVL": 3, 
         "Create_Date": "2015-01-21 09.48.44.387", 
         "ID_Specialty": 101
        }, 
        {
         "Spec_Source": "Project Metadata", 
         "Specialty": "Urgent Care", 
         "specialty_abbr": "UC", 
         "Flag_Acute": "N", 
         "Flag_Ambulatory": null, 
         "Parent_Specialty": 49, 
         "Flag_PrimaryCare": "N", 
         "Specialty_LVL": 3, 
         "Create_Date": "2015-01-21 09.48.44.387", 
         "ID_Specialty": 103
        }, 
        {
         "Spec_Source": "Project Metadata", 
         "Specialty": "Urology", 
         "specialty_abbr": "Urology", 
         "Flag_Acute": "Y", 
         "Flag_Ambulatory": null, 
         "Parent_Specialty": 50, 
         "Flag_PrimaryCare": "N", 
         "Specialty_LVL": 3, 
         "Create_Date": "2015-01-21 09.48.44.387", 
         "ID_Specialty": 104
        }, 
        {
         "Spec_Source": null, 
         "Specialty": " Not Specified", 
         "specialty_abbr": " Not Specified", 
         "Flag_Acute": "Y", 
         "Flag_Ambulatory": null, 
         "Parent_Specialty": null, 
         "Flag_PrimaryCare": null, 
         "Specialty_LVL": 3, 
         "Create_Date": null, 
         "ID_Specialty": 108
        }, 
        {
         "Spec_Source": "Manual Add", 
         "Specialty": "Sleep Medicine", 
         "specialty_abbr": "Sleep Medicine", 
         "Flag_Acute": "Y", 
         "Flag_Ambulatory": null, 
         "Parent_Specialty": 118, 
         "Flag_PrimaryCare": "N", 
         "Specialty_LVL": 3, 
         "Create_Date": "2015-08-06 00.00.00.000", 
         "ID_Specialty": 119
        }, 
        {
         "Spec_Source": "Manual Add", 
         "Specialty": "Registered Nurse", 
         "specialty_abbr": "Nurse", 
         "Flag_Acute": "Y", 
         "Flag_Ambulatory": null, 
         "Parent_Specialty": 121, 
         "Flag_PrimaryCare": "N", 
         "Specialty_LVL": 3, 
         "Create_Date": "2016-11-02 13.03.24.837", 
         "ID_Specialty": 122
        }, 
        {
         "Spec_Source": "Roster", 
         "Specialty": "Acupuncture", 
         "specialty_abbr": "Acupuncture", 
         "Flag_Acute": "N", 
         "Flag_Ambulatory": null, 
         "Parent_Specialty": 163, 
         "Flag_PrimaryCare": "N", 
         "Specialty_LVL": 3, 
         "Create_Date": "2017-02-15 13.20.24.730", 
         "ID_Specialty": 171
        }, 
        {
         "Spec_Source": "Roster", 
         "Specialty": "Audiology", 
         "specialty_abbr": "Audiology", 
         "Flag_Acute": "N", 
         "Flag_Ambulatory": null, 
         "Parent_Specialty": 164, 
         "Flag_PrimaryCare": "N", 
         "Specialty_LVL": 3, 
         "Create_Date": "2017-02-15 13.20.24.730", 
         "ID_Specialty": 172
        }, 
        {
         "Spec_Source": "Roster", 
         "Specialty": "Medical Genetics and Genomics", 
         "specialty_abbr": "Genetics", 
         "Flag_Acute": "N", 
         "Flag_Ambulatory": null, 
         "Parent_Specialty": 165, 
         "Flag_PrimaryCare": "N", 
         "Specialty_LVL": 3, 
         "Create_Date": "2017-02-15 13.20.24.730", 
         "ID_Specialty": 173
        }, 
        {
         "Spec_Source": "Roster", 
         "Specialty": "Occupational Medicine", 
         "specialty_abbr": "Occupational Medicine", 
         "Flag_Acute": "N", 
         "Flag_Ambulatory": null, 
         "Parent_Specialty": 168, 
         "Flag_PrimaryCare": "N", 
         "Specialty_LVL": 3, 
         "Create_Date": "2017-02-15 13.20.24.730", 
         "ID_Specialty": 176
        }, 
        {
         "Spec_Source": "Roster", 
         "Specialty": "Pathology", 
         "specialty_abbr": "Pathology", 
         "Flag_Acute": "N", 
         "Flag_Ambulatory": null, 
         "Parent_Specialty": 170, 
         "Flag_PrimaryCare": "N", 
         "Specialty_LVL": 3, 
         "Create_Date": "2017-02-15 13.20.24.730", 
         "ID_Specialty": 178
        }, 
        {
         "Spec_Source": "Roster", 
         "Specialty": "Neuroscience", 
         "specialty_abbr": "Neuroscience", 
         "Flag_Acute": "N", 
         "Flag_Ambulatory": null, 
         "Parent_Specialty": 189, 
         "Flag_PrimaryCare": "N", 
         "Specialty_LVL": 3, 
         "Create_Date": "2017-08-24 08.02.12.377", 
         "ID_Specialty": 190
        }, 
        {
         "Spec_Source": "Specialty Reorganization", 
         "Specialty": "Hospice and Palliative Medicine", 
         "specialty_abbr": "Hospice", 
         "Flag_Acute": null, 
         "Flag_Ambulatory": null, 
         "Parent_Specialty": 202, 
         "Flag_PrimaryCare": null, 
         "Specialty_LVL": 3, 
         "Create_Date": "2021-02-01 08.21.22.607", 
         "ID_Specialty": 208
        }, 
        {
         "Spec_Source": "Specialty Reorganization", 
         "Specialty": "Hospital Medicine", 
         "specialty_abbr": "Hospital Medicine", 
         "Flag_Acute": null, 
         "Flag_Ambulatory": null, 
         "Parent_Specialty": 203, 
         "Flag_PrimaryCare": null, 
         "Specialty_LVL": 3, 
         "Create_Date": "2021-02-01 08.21.22.607", 
         "ID_Specialty": 209
        }, 
        {
         "Spec_Source": "Specialty Reorganization", 
         "Specialty": "Mental Health Services", 
         "specialty_abbr": "Mental Health", 
         "Flag_Acute": null, 
         "Flag_Ambulatory": null, 
         "Parent_Specialty": 204, 
         "Flag_PrimaryCare": null, 
         "Specialty_LVL": 3, 
         "Create_Date": "2021-02-01 08.21.22.607", 
         "ID_Specialty": 210
        }, 
        {
         "Spec_Source": "Specialty Reorganization", 
         "Specialty": "Nuclear Medicine", 
         "specialty_abbr": "Nuclear Medicine", 
         "Flag_Acute": null, 
         "Flag_Ambulatory": null, 
         "Parent_Specialty": 205, 
         "Flag_PrimaryCare": null, 
         "Specialty_LVL": 3, 
         "Create_Date": "2021-02-01 08.21.22.607", 
         "ID_Specialty": 211
        }, 
        {
         "Spec_Source": "Specialty Reorganization", 
         "Specialty": "Optometry", 
         "specialty_abbr": "Optometry", 
         "Flag_Acute": null, 
         "Flag_Ambulatory": null, 
         "Parent_Specialty": 206, 
         "Flag_PrimaryCare": null, 
         "Specialty_LVL": 3, 
         "Create_Date": "2021-02-01 08.21.22.607", 
         "ID_Specialty": 212
        }
       ]
}
exports.get = Dim_Specialty
