const LoremIpsum = require("lorem-ipsum").LoremIpsum;

const lorem = new LoremIpsum({
    sentencesPerParagraph: {
      max: 8,
      min: 4
    },
    wordsPerSentence: {
      max: 16,
      min: 4
    }
  });

let DimProject = function() {
    return [
        {
         "ID_LeadPhysician": "StevensonD",
         "FL_Mature": null, 
         "DESC_ProjectCategory": null, 
         "ID_ProjectDim": 4917, 
         "DT_ProjectStartDate": "2020-07-01 00.00.00.000", 
         "DESC_ProjectIntervention": null, 
         "ID_TemplateProject": 750, 
         "DESC_Foundation": null, 
         "DT_DataStartDate": "2019-07-01 00.00.00.000",
         "FL_ActiveProject": 1, 
         "FL_SendEmail": 9, 
         "DTTM_Update": null, 
         "ID_ProjectType": 4, 
         "FL_GroupReport": null, 
         "ID_ProjectStatus": 1, 
         "ID_ParentProject": null, 
         "FL_EPR": 1, 
         "DESC_ProjectTopic": null, 
         "ID_Specialty": 82, 
         "ADDR_ProvCity": null,
         "DESC_ProjectType": "Labs",
         "DT_DataLoadDate": "2020-06-17 10.00.49.000", 
         "FL_Population": null, 
         "DT_ProjectEndDate": "2022-07-01 00.00.00.000", 
         "ID_Champion": "GibbsD", 
         "DESC_ProvSpec": "Pediatrics", 
         "DESC_LeadPhysician": null, 
         "DESC_Region": null, 
         "DTTM_Insert": "2020-06-17 10.00.59.510", 
         "DESC_ProvGroup": null, 
         "Project_Standard_Details": null, 
         "DESC_MedicalGroup": null, 
         "ID_BusinessAnalyst": "MorrisF",
         "FL_Achieving": null, 
         "DESC_ProjectStatus": "Adopted", 
         "DT_ProjectRetireDate": null, 
         "ID_ProjectSetting": 2, 
         "DT_DataExpireDate": null,
         "DESC_ProjectName":  lorem.generateSentences(1),
         "DESC_ProblemStatement":  lorem.generateSentences(1),
         "DESC_ProjectStandard":  lorem.generateSentences(1),
         "DESC_GoalStatement":  lorem.generateSentences(1),
         "DESC_Appendix":  lorem.generateSentences(1),
        }, 
        {
         "ID_LeadPhysician": "HartB",
         "FL_Mature": null, 
         "DESC_ProjectCategory": null, 
         "ID_ProjectDim": 4920, 
         "DT_ProjectStartDate": "2020-07-01 00.00.00.000", 
         "DESC_ProjectIntervention": null, 
         "ID_TemplateProject": 751, 
         "DESC_Foundation": null, 
         "DT_DataStartDate": "2019-07-01 00.00.00.000",
         "FL_ActiveProject": 1, 
         "FL_SendEmail": 5, 
         "DTTM_Update": null, 
         "ID_ProjectType": 13, 
         "FL_GroupReport": null, 
         "ID_ProjectStatus": 9, 
         "ID_ParentProject": null, 
         "FL_EPR": 1, 
         "DESC_ProjectTopic": null, 
         "ID_Specialty": 78, 
         "ADDR_ProvCity": null,
         "DESC_ProjectType": "Monitoring",
         "DT_DataLoadDate": "2020-06-17 16.36.32.000", 
         "FL_Population": null, 
         "DT_ProjectEndDate": "2022-07-01 00.00.00.000", 
         "ID_Champion": "HartB", 
         "DESC_ProvSpec": "Oncology", 
         "DESC_LeadPhysician": null, 
         "DESC_Region": null, 
         "DTTM_Insert": "2020-06-17 16.36.40.343", 
         "DESC_ProvGroup": null, 
         "Project_Standard_Details": null, 
         "DESC_MedicalGroup": null, 
         "ID_BusinessAnalyst": "LawsonN",
         "FL_Achieving": null, 
         "DESC_ProjectStatus": "Data Shared", 
         "DT_ProjectRetireDate": null, 
         "ID_ProjectSetting": 1, 
         "DT_DataExpireDate": null,
         "DESC_ProjectName":  lorem.generateSentences(1),
         "DESC_ProblemStatement":  lorem.generateSentences(1),
         "DESC_ProjectStandard":  lorem.generateSentences(1),
         "DESC_GoalStatement":  lorem.generateSentences(1),
         "DESC_Appendix":  lorem.generateSentences(1),
        }, 
        {
         "ID_LeadPhysician": "ReedC",
         "FL_Mature": null, 
         "DESC_ProjectCategory": null, 
         "ID_ProjectDim": 5028, 
         "DT_ProjectStartDate": "2020-07-01 00.00.00.000", 
         "DESC_ProjectIntervention": null, 
         "ID_TemplateProject": 752, 
         "DESC_Foundation": null, 
         "DT_DataStartDate": "2019-07-01 00.00.00.000",
         "FL_ActiveProject": 1, 
         "FL_SendEmail": 1, 
         "DTTM_Update": null, 
         "ID_ProjectType": 10, 
         "FL_GroupReport": null, 
         "ID_ProjectStatus": 1, 
         "ID_ParentProject": null, 
         "FL_EPR": 1, 
         "DESC_ProjectTopic": null, 
         "ID_Specialty": 77, 
         "ADDR_ProvCity": null,
         "DESC_ProjectType": "Visits",
         "DT_DataLoadDate": "2020-07-22 09.58.49.000", 
         "FL_Population": null, 
         "DT_ProjectEndDate": "2022-07-01 00.00.00.000", 
         "ID_Champion": "WaltonJ", 
         "DESC_ProvSpec": "Obstetrics and Gynecology", 
         "DESC_LeadPhysician": null, 
         "DESC_Region": null, 
         "DTTM_Insert": "2020-07-22 09.58.55.897", 
         "DESC_ProvGroup": null, 
         "Project_Standard_Details": null, 
         "DESC_MedicalGroup": null, 
         "ID_BusinessAnalyst": "BurkeD",
         "FL_Achieving": null, 
         "DESC_ProjectStatus": "Adopted", 
         "DT_ProjectRetireDate": null, 
         "ID_ProjectSetting": 1, 
         "DT_DataExpireDate": null,
         "DESC_ProjectName":  lorem.generateSentences(1),
         "DESC_ProblemStatement":  lorem.generateSentences(1),
         "DESC_ProjectStandard":  lorem.generateSentences(1),
         "DESC_GoalStatement":  lorem.generateSentences(1),
         "DESC_Appendix":  lorem.generateSentences(1),
        }, 
        {
         "ID_LeadPhysician": "ReedC",
         "FL_Mature": null, 
         "DESC_ProjectCategory": null, 
         "ID_ProjectDim": 5029, 
         "DT_ProjectStartDate": "2020-07-01 00.00.00.000", 
         "DESC_ProjectIntervention": null, 
         "ID_TemplateProject": 753, 
         "DESC_Foundation": null, 
         "DT_DataStartDate": "2019-07-01 00.00.00.000",
         "FL_ActiveProject": 1, 
         "FL_SendEmail": 1, 
         "DTTM_Update": null, 
         "ID_ProjectType": 10, 
         "FL_GroupReport": null, 
         "ID_ProjectStatus": 1, 
         "ID_ParentProject": null, 
         "FL_EPR": 1, 
         "DESC_ProjectTopic": null, 
         "ID_Specialty": 77, 
         "ADDR_ProvCity": null,
         "DESC_ProjectType": "Visits",
         "DT_DataLoadDate": "2020-07-22 10.05.01.000", 
         "FL_Population": null, 
         "DT_ProjectEndDate": "2022-07-01 00.00.00.000", 
         "ID_Champion": "WaltonJ", 
         "DESC_ProvSpec": "Obstetrics and Gynecology", 
         "DESC_LeadPhysician": null, 
         "DESC_Region": null, 
         "DTTM_Insert": "2020-07-22 10.05.07.350", 
         "DESC_ProvGroup": null, 
         "Project_Standard_Details": null, 
         "DESC_MedicalGroup": null, 
         "ID_BusinessAnalyst": "BurkeD",
         "FL_Achieving": null, 
         "DESC_ProjectStatus": "Adopted", 
         "DT_ProjectRetireDate": null, 
         "ID_ProjectSetting": 1, 
         "DT_DataExpireDate": null,
         "DESC_ProjectName":  lorem.generateSentences(1),
         "DESC_ProblemStatement":  lorem.generateSentences(1),
         "DESC_ProjectStandard":  lorem.generateSentences(1),
         "DESC_GoalStatement":  lorem.generateSentences(1),
         "DESC_Appendix":  lorem.generateSentences(1),
        }, 
        {
         "ID_LeadPhysician": "RayJ",
         "FL_Mature": null, 
         "DESC_ProjectCategory": null, 
         "ID_ProjectDim": 5044, 
         "DT_ProjectStartDate": "2020-08-03 00.00.00.000", 
         "DESC_ProjectIntervention": null, 
         "ID_TemplateProject": 754, 
         "DESC_Foundation": null, 
         "DT_DataStartDate": "2019-08-01 00.00.00.000",
         "FL_ActiveProject": 1, 
         "FL_SendEmail": 1, 
         "DTTM_Update": null, 
         "ID_ProjectType": 6, 
         "FL_GroupReport": null, 
         "ID_ProjectStatus": 1, 
         "ID_ParentProject": null, 
         "FL_EPR": 1, 
         "DESC_ProjectTopic": null, 
         "ID_Specialty": 99, 
         "ADDR_ProvCity": null,
         "DESC_ProjectType": "Pharmacy",
         "DT_DataLoadDate": "2020-08-12 09.39.14.000", 
         "FL_Population": null, 
         "DT_ProjectEndDate": "2022-08-01 00.00.00.000", 
         "ID_Champion": "PatrickB", 
         "DESC_ProvSpec": "Surgery", 
         "DESC_LeadPhysician": null, 
         "DESC_Region": null, 
         "DTTM_Insert": "2020-08-12 09.39.46.867", 
         "DESC_ProvGroup": null, 
         "Project_Standard_Details": null, 
         "DESC_MedicalGroup": null, 
         "ID_BusinessAnalyst": "BurkeD",
         "FL_Achieving": null, 
         "DESC_ProjectStatus": "Adopted", 
         "DT_ProjectRetireDate": null, 
         "ID_ProjectSetting": 1, 
         "DT_DataExpireDate": null,
         "DESC_ProjectName":  lorem.generateSentences(1),
         "DESC_ProblemStatement":  lorem.generateSentences(1),
         "DESC_ProjectStandard":  lorem.generateSentences(1),
         "DESC_GoalStatement":  lorem.generateSentences(1),
         "DESC_Appendix":  lorem.generateSentences(1),
        }, 
        {
         "ID_LeadPhysician": "BarnesK",
         "FL_Mature": null, 
         "DESC_ProjectCategory": null, 
         "ID_ProjectDim": 5045, 
         "DT_ProjectStartDate": "2020-08-03 00.00.00.000", 
         "DESC_ProjectIntervention": null, 
         "ID_TemplateProject": 755, 
         "DESC_Foundation": null, 
         "DT_DataStartDate": "2019-08-01 00.00.00.000",
         "FL_ActiveProject": 1, 
         "FL_SendEmail": 1, 
         "DTTM_Update": null, 
         "ID_ProjectType": 6, 
         "FL_GroupReport": null, 
         "ID_ProjectStatus": 1, 
         "ID_ParentProject": null, 
         "FL_EPR": 1, 
         "DESC_ProjectTopic": null, 
         "ID_Specialty": 99, 
         "ADDR_ProvCity": null,
         "DESC_ProjectType": "Pharmacy",
         "DT_DataLoadDate": "2020-08-12 09.47.52.000", 
         "FL_Population": null, 
         "DT_ProjectEndDate": "2022-08-01 00.00.00.000", 
         "ID_Champion": null, 
         "DESC_ProvSpec": "Surgery", 
         "DESC_LeadPhysician": null, 
         "DESC_Region": null, 
         "DTTM_Insert": "2020-08-12 09.47.54.543", 
         "DESC_ProvGroup": null, 
         "Project_Standard_Details": null, 
         "DESC_MedicalGroup": null, 
         "ID_BusinessAnalyst": "BurkeD",
         "FL_Achieving": null, 
         "DESC_ProjectStatus": "Adopted", 
         "DT_ProjectRetireDate": null, 
         "ID_ProjectSetting": 1, 
         "DT_DataExpireDate": null,
         "DESC_ProjectName":  lorem.generateSentences(1),
         "DESC_ProblemStatement":  lorem.generateSentences(1),
         "DESC_ProjectStandard":  lorem.generateSentences(1),
         "DESC_GoalStatement":  lorem.generateSentences(1),
         "DESC_Appendix":  lorem.generateSentences(1),
        }, 
        {
         "ID_LeadPhysician": "HopkinsL",
         "FL_Mature": null, 
         "DESC_ProjectCategory": null, 
         "ID_ProjectDim": 5046, 
         "DT_ProjectStartDate": "2020-08-03 00.00.00.000", 
         "DESC_ProjectIntervention": null, 
         "ID_TemplateProject": 756, 
         "DESC_Foundation": null, 
         "DT_DataStartDate": "2019-08-01 00.00.00.000",
         "FL_ActiveProject": 1, 
         "FL_SendEmail": 1, 
         "DTTM_Update": null, 
         "ID_ProjectType": 6, 
         "FL_GroupReport": null, 
         "ID_ProjectStatus": 1, 
         "ID_ParentProject": null, 
         "FL_EPR": 1, 
         "DESC_ProjectTopic": null, 
         "ID_Specialty": 80, 
         "ADDR_ProvCity": null,
         "DESC_ProjectType": "Pharmacy",
         "DT_DataLoadDate": "2020-08-12 09.52.52.000", 
         "FL_Population": null, 
         "DT_ProjectEndDate": "2022-08-01 00.00.00.000", 
         "ID_Champion": "PatrickB", 
         "DESC_ProvSpec": "Orthopedics", 
         "DESC_LeadPhysician": null, 
         "DESC_Region": null, 
         "DTTM_Insert": "2020-08-12 09.53.14.700", 
         "DESC_ProvGroup": null, 
         "Project_Standard_Details": null, 
         "DESC_MedicalGroup": null, 
         "ID_BusinessAnalyst": "BurkeD",
         "FL_Achieving": null, 
         "DESC_ProjectStatus": "Adopted", 
         "DT_ProjectRetireDate": null, 
         "ID_ProjectSetting": 1, 
         "DT_DataExpireDate": null,
         "DESC_ProjectName":  lorem.generateSentences(1),
         "DESC_ProblemStatement":  lorem.generateSentences(1),
         "DESC_ProjectStandard":  lorem.generateSentences(1),
         "DESC_GoalStatement":  lorem.generateSentences(1),
         "DESC_Appendix":  lorem.generateSentences(1),
        }, 
        {
         "ID_LeadPhysician": "GillJ",
         "FL_Mature": null, 
         "DESC_ProjectCategory": null, 
         "ID_ProjectDim": 5053, 
         "DT_ProjectStartDate": "2020-07-01 00.00.00.000", 
         "DESC_ProjectIntervention": null, 
         "ID_TemplateProject": 757, 
         "DESC_Foundation": null, 
         "DT_DataStartDate": "2019-07-01 00.00.00.000",
         "FL_ActiveProject": 1, 
         "FL_SendEmail": 9, 
         "DTTM_Update": null, 
         "ID_ProjectType": 6, 
         "FL_GroupReport": null, 
         "ID_ProjectStatus": 1, 
         "ID_ParentProject": null, 
         "FL_EPR": 0, 
         "DESC_ProjectTopic": null, 
         "ID_Specialty": 190, 
         "ADDR_ProvCity": null,
         "DESC_ProjectType": "Pharmacy",
         "DT_DataLoadDate": "2020-09-30 12.47.55.000", 
         "FL_Population": null, 
         "DT_ProjectEndDate": "2022-07-01 00.00.00.000", 
         "ID_Champion": "MaxwellP", 
         "DESC_ProvSpec": "Neuroscience", 
         "DESC_LeadPhysician": null, 
         "DESC_Region": null, 
         "DTTM_Insert": "2020-09-30 12.47.56.753", 
         "DESC_ProvGroup": null, 
         "Project_Standard_Details": null, 
         "DESC_MedicalGroup": null, 
         "ID_BusinessAnalyst": "MorrisF",
         "FL_Achieving": null, 
         "DESC_ProjectStatus": "Adopted", 
         "DT_ProjectRetireDate": null, 
         "ID_ProjectSetting": 2, 
         "DT_DataExpireDate": null,
         "DESC_ProjectName":  lorem.generateSentences(1),
         "DESC_ProblemStatement":  lorem.generateSentences(1),
         "DESC_ProjectStandard":  lorem.generateSentences(1),
         "DESC_GoalStatement":  lorem.generateSentences(1),
         "DESC_Appendix":  lorem.generateSentences(1),
        }, 
        {
         "ID_LeadPhysician": "WhiteE",
         "FL_Mature": null, 
         "DESC_ProjectCategory": null, 
         "ID_ProjectDim": 5054, 
         "DT_ProjectStartDate": "2020-10-01 00.00.00.000", 
         "DESC_ProjectIntervention": null, 
         "ID_TemplateProject": 758, 
         "DESC_Foundation": null, 
         "DT_DataStartDate": "2019-10-01 00.00.00.000",
         "FL_ActiveProject": 1, 
         "FL_SendEmail": 1, 
         "DTTM_Update": null, 
         "ID_ProjectType": 6, 
         "FL_GroupReport": null, 
         "ID_ProjectStatus": 1, 
         "ID_ParentProject": null, 
         "FL_EPR": 1, 
         "DESC_ProjectTopic": null, 
         "ID_Specialty": 59, 
         "ADDR_ProvCity": null,
         "DESC_ProjectType": "Pharmacy",
         "DT_DataLoadDate": "2020-10-07 11.26.40.000", 
         "FL_Population": null, 
         "DT_ProjectEndDate": "2022-10-01 00.00.00.000", 
         "ID_Champion": "SteeleP", 
         "DESC_ProvSpec": "Endocrinology", 
         "DESC_LeadPhysician": null, 
         "DESC_Region": null, 
         "DTTM_Insert": "2020-10-07 11.27.11.970", 
         "DESC_ProvGroup": null, 
         "Project_Standard_Details": null, 
         "DESC_MedicalGroup": null, 
         "ID_BusinessAnalyst": "MorrisF",
         "FL_Achieving": null, 
         "DESC_ProjectStatus": "Adopted", 
         "DT_ProjectRetireDate": null, 
         "ID_ProjectSetting": 1, 
         "DT_DataExpireDate": null,
         "DESC_ProjectName":  lorem.generateSentences(1),
         "DESC_ProblemStatement":  lorem.generateSentences(1),
         "DESC_ProjectStandard":  lorem.generateSentences(1),
         "DESC_GoalStatement":  lorem.generateSentences(1),
         "DESC_Appendix":  lorem.generateSentences(1),
        }, 
        {
         "ID_LeadPhysician": "LindseyG",
         "FL_Mature": null, 
         "DESC_ProjectCategory": null, 
         "ID_ProjectDim": 5055, 
         "DT_ProjectStartDate": "2020-10-01 00.00.00.000", 
         "DESC_ProjectIntervention": null, 
         "ID_TemplateProject": 758, 
         "DESC_Foundation": null, 
         "DT_DataStartDate": "2019-10-01 00.00.00.000",
         "FL_ActiveProject": 1, 
         "FL_SendEmail": 1, 
         "DTTM_Update": null, 
         "ID_ProjectType": 6, 
         "FL_GroupReport": null, 
         "ID_ProjectStatus": 1, 
         "ID_ParentProject": null, 
         "FL_EPR": 1, 
         "DESC_ProjectTopic": null, 
         "ID_Specialty": 55, 
         "ADDR_ProvCity": null,
         "DESC_ProjectType": "Pharmacy",
         "DT_DataLoadDate": "2020-10-07 12.56.35.000", 
         "FL_Population": null, 
         "DT_ProjectEndDate": "2022-10-01 00.00.00.000", 
         "ID_Champion": "SteeleP", 
         "DESC_ProvSpec": "Cardiology", 
         "DESC_LeadPhysician": null, 
         "DESC_Region": null, 
         "DTTM_Insert": "2020-10-07 12.56.39.960", 
         "DESC_ProvGroup": null, 
         "Project_Standard_Details": null, 
         "DESC_MedicalGroup": null, 
         "ID_BusinessAnalyst": "MorrisF",
         "FL_Achieving": null, 
         "DESC_ProjectStatus": "Adopted", 
         "DT_ProjectRetireDate": null, 
         "ID_ProjectSetting": 1, 
         "DT_DataExpireDate": null,
         "DESC_ProjectName":  lorem.generateSentences(1),
         "DESC_ProblemStatement":  lorem.generateSentences(1),
         "DESC_ProjectStandard":  lorem.generateSentences(1),
         "DESC_GoalStatement":  lorem.generateSentences(1),
         "DESC_Appendix":  lorem.generateSentences(1),
        }, 
        {
         "ID_LeadPhysician": "CollierO",
         "FL_Mature": null, 
         "DESC_ProjectCategory": null, 
         "ID_ProjectDim": 5058, 
         "DT_ProjectStartDate": "2020-02-11 00.00.00.000", 
         "DESC_ProjectIntervention": null, 
         "ID_TemplateProject": 758, 
         "DESC_Foundation": null, 
         "DT_DataStartDate": "2019-02-01 00.00.00.000",
         "FL_ActiveProject": 1, 
         "FL_SendEmail": 1, 
         "DTTM_Update": null, 
         "ID_ProjectType": 6, 
         "FL_GroupReport": null, 
         "ID_ProjectStatus": 1, 
         "ID_ParentProject": null, 
         "FL_EPR": 1, 
         "DESC_ProjectTopic": null, 
         "ID_Specialty": 61, 
         "ADDR_ProvCity": null,
         "DESC_ProjectType": "Pharmacy",
         "DT_DataLoadDate": "2020-10-29 11.55.04.000", 
         "FL_Population": null, 
         "DT_ProjectEndDate": "2022-02-01 00.00.00.000", 
         "ID_Champion": "SteeleP", 
         "DESC_ProvSpec": "Family Medicine", 
         "DESC_LeadPhysician": null, 
         "DESC_Region": null, 
         "DTTM_Insert": "2020-10-29 11.55.06.520", 
         "DESC_ProvGroup": null, 
         "Project_Standard_Details": null, 
         "DESC_MedicalGroup": null, 
         "ID_BusinessAnalyst": "MorrisF",
         "FL_Achieving": null, 
         "DESC_ProjectStatus": "Adopted", 
         "DT_ProjectRetireDate": null, 
         "ID_ProjectSetting": 1, 
         "DT_DataExpireDate": null,
         "DESC_ProjectName":  lorem.generateSentences(1),
         "DESC_ProblemStatement":  lorem.generateSentences(1),
         "DESC_ProjectStandard":  lorem.generateSentences(1),
         "DESC_GoalStatement":  lorem.generateSentences(1),
         "DESC_Appendix":  lorem.generateSentences(1),
        }, 
        {
         "ID_LeadPhysician": "LucasD",
         "FL_Mature": null, 
         "DESC_ProjectCategory": null, 
         "ID_ProjectDim": 5059, 
         "DT_ProjectStartDate": "2020-02-11 00.00.00.000", 
         "DESC_ProjectIntervention": null, 
         "ID_TemplateProject": 758, 
         "DESC_Foundation": null, 
         "DT_DataStartDate": "2019-02-01 00.00.00.000",
         "FL_ActiveProject": 1, 
         "FL_SendEmail": 1, 
         "DTTM_Update": null, 
         "ID_ProjectType": 6, 
         "FL_GroupReport": null, 
         "ID_ProjectStatus": 1, 
         "ID_ParentProject": null, 
         "FL_EPR": 1, 
         "DESC_ProjectTopic": null, 
         "ID_Specialty": 61, 
         "ADDR_ProvCity": null,
         "DESC_ProjectType": "Pharmacy",
         "DT_DataLoadDate": "2020-10-29 12.38.35.000", 
         "FL_Population": null, 
         "DT_ProjectEndDate": "2022-02-01 00.00.00.000", 
         "ID_Champion": "SteeleP", 
         "DESC_ProvSpec": "Family Medicine", 
         "DESC_LeadPhysician": null, 
         "DESC_Region": null, 
         "DTTM_Insert": "2020-10-29 12.38.40.590", 
         "DESC_ProvGroup": null, 
         "Project_Standard_Details": null, 
         "DESC_MedicalGroup": null, 
         "ID_BusinessAnalyst": "MorrisF",
         "FL_Achieving": null, 
         "DESC_ProjectStatus": "Adopted", 
         "DT_ProjectRetireDate": null, 
         "ID_ProjectSetting": 1, 
         "DT_DataExpireDate": null,
         "DESC_ProjectName":  lorem.generateSentences(1),
         "DESC_ProblemStatement":  lorem.generateSentences(1),
         "DESC_ProjectStandard":  lorem.generateSentences(1),
         "DESC_GoalStatement":  lorem.generateSentences(1),
         "DESC_Appendix":  lorem.generateSentences(1),
        }, 
        {
         "ID_LeadPhysician": "GregoryJ",
         "FL_Mature": null, 
         "DESC_ProjectCategory": null, 
         "ID_ProjectDim": 5060, 
         "DT_ProjectStartDate": "2020-02-11 00.00.00.000", 
         "DESC_ProjectIntervention": null, 
         "ID_TemplateProject": 758, 
         "DESC_Foundation": null, 
         "DT_DataStartDate": "2019-02-01 00.00.00.000",
         "FL_ActiveProject": 1, 
         "FL_SendEmail": 1, 
         "DTTM_Update": null, 
         "ID_ProjectType": 6, 
         "FL_GroupReport": null, 
         "ID_ProjectStatus": 1, 
         "ID_ParentProject": null, 
         "FL_EPR": 1, 
         "DESC_ProjectTopic": null, 
         "ID_Specialty": 61, 
         "ADDR_ProvCity": null,
         "DESC_ProjectType": "Pharmacy",
         "DT_DataLoadDate": "2020-10-29 12.50.54.000", 
         "FL_Population": null, 
         "DT_ProjectEndDate": "2022-02-01 00.00.00.000", 
         "ID_Champion": "SteeleP", 
         "DESC_ProvSpec": "Family Medicine", 
         "DESC_LeadPhysician": null, 
         "DESC_Region": null, 
         "DTTM_Insert": "2020-10-29 12.51.01.810", 
         "DESC_ProvGroup": null, 
         "Project_Standard_Details": null, 
         "DESC_MedicalGroup": null, 
         "ID_BusinessAnalyst": "MorrisF",
         "FL_Achieving": null, 
         "DESC_ProjectStatus": "Adopted", 
         "DT_ProjectRetireDate": null, 
         "ID_ProjectSetting": 1, 
         "DT_DataExpireDate": null,
         "DESC_ProjectName":  lorem.generateSentences(1),
         "DESC_ProblemStatement":  lorem.generateSentences(1),
         "DESC_ProjectStandard":  lorem.generateSentences(1),
         "DESC_GoalStatement":  lorem.generateSentences(1),
         "DESC_Appendix":  lorem.generateSentences(1),
        }, 
        {
         "ID_LeadPhysician": "LucasD",
         "FL_Mature": null, 
         "DESC_ProjectCategory": null, 
         "ID_ProjectDim": 5061, 
         "DT_ProjectStartDate": "2020-02-11 00.00.00.000", 
         "DESC_ProjectIntervention": null, 
         "ID_TemplateProject": 758, 
         "DESC_Foundation": null, 
         "DT_DataStartDate": "2019-02-01 00.00.00.000",
         "FL_ActiveProject": 1, 
         "FL_SendEmail": 1, 
         "DTTM_Update": null, 
         "ID_ProjectType": 6, 
         "FL_GroupReport": null, 
         "ID_ProjectStatus": 1, 
         "ID_ParentProject": null, 
         "FL_EPR": 1, 
         "DESC_ProjectTopic": null, 
         "ID_Specialty": 70, 
         "ADDR_ProvCity": null,
         "DESC_ProjectType": "Pharmacy",
         "DT_DataLoadDate": "2020-10-29 12.57.46.000", 
         "FL_Population": null, 
         "DT_ProjectEndDate": "2022-02-01 00.00.00.000", 
         "ID_Champion": "SteeleP", 
         "DESC_ProvSpec": "Internal Medicine", 
         "DESC_LeadPhysician": null, 
         "DESC_Region": null, 
         "DTTM_Insert": "2020-10-29 12.57.51.080", 
         "DESC_ProvGroup": null, 
         "Project_Standard_Details": null, 
         "DESC_MedicalGroup": null, 
         "ID_BusinessAnalyst": "MorrisF",
         "FL_Achieving": null, 
         "DESC_ProjectStatus": "Adopted", 
         "DT_ProjectRetireDate": null, 
         "ID_ProjectSetting": 1, 
         "DT_DataExpireDate": null,
         "DESC_ProjectName":  lorem.generateSentences(1),
         "DESC_ProblemStatement":  lorem.generateSentences(1),
         "DESC_ProjectStandard":  lorem.generateSentences(1),
         "DESC_GoalStatement":  lorem.generateSentences(1),
         "DESC_Appendix":  lorem.generateSentences(1),
        }, 
        {
         "ID_LeadPhysician": "SteeleP",
         "FL_Mature": null, 
         "DESC_ProjectCategory": null, 
         "ID_ProjectDim": 5062, 
         "DT_ProjectStartDate": "2020-02-11 00.00.00.000", 
         "DESC_ProjectIntervention": null, 
         "ID_TemplateProject": 758, 
         "DESC_Foundation": null, 
         "DT_DataStartDate": "2019-02-01 00.00.00.000",
         "FL_ActiveProject": 1, 
         "FL_SendEmail": 9, 
         "DTTM_Update": null, 
         "ID_ProjectType": 6, 
         "FL_GroupReport": null, 
         "ID_ProjectStatus": 11, 
         "ID_ParentProject": null, 
         "FL_EPR": 1, 
         "DESC_ProjectTopic": null, 
         "ID_Specialty": 61, 
         "ADDR_ProvCity": null,
         "DESC_ProjectType": "Pharmacy",
         "DT_DataLoadDate": "2020-10-29 13.07.29.000", 
         "FL_Population": null, 
         "DT_ProjectEndDate": "2022-02-01 00.00.00.000", 
         "ID_Champion": "SteeleP", 
         "DESC_ProvSpec": "Family Medicine", 
         "DESC_LeadPhysician": null, 
         "DESC_Region": null, 
         "DTTM_Insert": "2020-10-29 13.07.35.030", 
         "DESC_ProvGroup": null, 
         "Project_Standard_Details": null, 
         "DESC_MedicalGroup": null, 
         "ID_BusinessAnalyst": "MorrisF",
         "FL_Achieving": null, 
         "DESC_ProjectStatus": "Dashboard Rollup", 
         "DT_ProjectRetireDate": null, 
         "ID_ProjectSetting": 1, 
         "DT_DataExpireDate": null,
         "DESC_ProjectName":  lorem.generateSentences(1),
         "DESC_ProblemStatement":  lorem.generateSentences(1),
         "DESC_ProjectStandard":  lorem.generateSentences(1),
         "DESC_GoalStatement":  lorem.generateSentences(1),
         "DESC_Appendix":  lorem.generateSentences(1),
        }, 
        {
         "ID_LeadPhysician": "SteeleP",
         "FL_Mature": null, 
         "DESC_ProjectCategory": null, 
         "ID_ProjectDim": 5063, 
         "DT_ProjectStartDate": "2020-02-21 00.00.00.000", 
         "DESC_ProjectIntervention": null, 
         "ID_TemplateProject": 758, 
         "DESC_Foundation": null, 
         "DT_DataStartDate": "2019-02-01 00.00.00.000",
         "FL_ActiveProject": 1, 
         "FL_SendEmail": 9, 
         "DTTM_Update": null, 
         "ID_ProjectType": 6, 
         "FL_GroupReport": null, 
         "ID_ProjectStatus": 11, 
         "ID_ParentProject": null, 
         "FL_EPR": 1, 
         "DESC_ProjectTopic": null, 
         "ID_Specialty": 70, 
         "ADDR_ProvCity": null,
         "DESC_ProjectType": "Pharmacy",
         "DT_DataLoadDate": "2020-10-29 13.12.20.000", 
         "FL_Population": null, 
         "DT_ProjectEndDate": "2022-02-01 00.00.00.000", 
         "ID_Champion": "SteeleP", 
         "DESC_ProvSpec": "Internal Medicine", 
         "DESC_LeadPhysician": null, 
         "DESC_Region": null, 
         "DTTM_Insert": "2020-10-29 13.12.26.240", 
         "DESC_ProvGroup": null, 
         "Project_Standard_Details": null, 
         "DESC_MedicalGroup": null, 
         "ID_BusinessAnalyst": "MorrisF",
         "FL_Achieving": null, 
         "DESC_ProjectStatus": "Dashboard Rollup", 
         "DT_ProjectRetireDate": null, 
         "ID_ProjectSetting": 1, 
         "DT_DataExpireDate": null,
         "DESC_ProjectName":  lorem.generateSentences(1),
         "DESC_ProblemStatement":  lorem.generateSentences(1),
         "DESC_ProjectStandard":  lorem.generateSentences(1),
         "DESC_GoalStatement":  lorem.generateSentences(1),
         "DESC_Appendix":  lorem.generateSentences(1),
        }, 
        {
         "ID_LeadPhysician": "NunezE",
         "FL_Mature": null, 
         "DESC_ProjectCategory": null, 
         "ID_ProjectDim": 5065, 
         "DT_ProjectStartDate": "2020-02-11 00.00.00.000", 
         "DESC_ProjectIntervention": null, 
         "ID_TemplateProject": 758, 
         "DESC_Foundation": null, 
         "DT_DataStartDate": "2019-02-01 00.00.00.000",
         "FL_ActiveProject": 1, 
         "FL_SendEmail": 1, 
         "DTTM_Update": null, 
         "ID_ProjectType": 6, 
         "FL_GroupReport": null, 
         "ID_ProjectStatus": 1, 
         "ID_ParentProject": null, 
         "FL_EPR": 1, 
         "DESC_ProjectTopic": null, 
         "ID_Specialty": 61, 
         "ADDR_ProvCity": null,
         "DESC_ProjectType": "Pharmacy",
         "DT_DataLoadDate": "2020-11-03 15.23.25.000", 
         "FL_Population": null, 
         "DT_ProjectEndDate": "2022-02-01 00.00.00.000", 
         "ID_Champion": "SteeleP", 
         "DESC_ProvSpec": "Family Medicine", 
         "DESC_LeadPhysician": null, 
         "DESC_Region": null, 
         "DTTM_Insert": "2020-11-03 15.23.31.543", 
         "DESC_ProvGroup": null, 
         "Project_Standard_Details": null, 
         "DESC_MedicalGroup": null, 
         "ID_BusinessAnalyst": "MorrisF",
         "FL_Achieving": null, 
         "DESC_ProjectStatus": "Adopted", 
         "DT_ProjectRetireDate": null, 
         "ID_ProjectSetting": 1, 
         "DT_DataExpireDate": null,
         "DESC_ProjectName":  lorem.generateSentences(1),
         "DESC_ProblemStatement":  lorem.generateSentences(1),
         "DESC_ProjectStandard":  lorem.generateSentences(1),
         "DESC_GoalStatement":  lorem.generateSentences(1),
         "DESC_Appendix":  lorem.generateSentences(1),
        }, 
        {
         "ID_LeadPhysician": "ThompsonD",
         "FL_Mature": null, 
         "DESC_ProjectCategory": null, 
         "ID_ProjectDim": 5804, 
         "DT_ProjectStartDate": "2021-01-01 00.00.00.000", 
         "DESC_ProjectIntervention": null, 
         "ID_TemplateProject": 760, 
         "DESC_Foundation": null, 
         "DT_DataStartDate": "2020-01-01 00.00.00.000",
         "FL_ActiveProject": 1, 
         "FL_SendEmail": 2, 
         "DTTM_Update": null, 
         "ID_ProjectType": 4, 
         "FL_GroupReport": null, 
         "ID_ProjectStatus": 1, 
         "ID_ParentProject": null, 
         "FL_EPR": 1, 
         "DESC_ProjectTopic": null, 
         "ID_Specialty": 77, 
         "ADDR_ProvCity": null,
         "DESC_ProjectType": "Labs",
         "DT_DataLoadDate": "2021-02-24 11.28.18.000", 
         "FL_Population": null, 
         "DT_ProjectEndDate": "2023-01-01 00.00.00.000", 
         "ID_Champion": "FisherN", 
         "DESC_ProvSpec": null, 
         "DESC_LeadPhysician": null, 
         "DESC_Region": null, 
         "DTTM_Insert": "2021-02-24 11.28.20.280", 
         "DESC_ProvGroup": null, 
         "Project_Standard_Details": null, 
         "DESC_MedicalGroup": null, 
         "ID_BusinessAnalyst": "MorrisF",
         "FL_Achieving": null, 
         "DESC_ProjectStatus": "Adopted", 
         "DT_ProjectRetireDate": null, 
         "ID_ProjectSetting": 1, 
         "DT_DataExpireDate": null,
         "DESC_ProjectName":  lorem.generateSentences(1),
         "DESC_ProblemStatement":  lorem.generateSentences(1),
         "DESC_ProjectStandard":  lorem.generateSentences(1),
         "DESC_GoalStatement":  lorem.generateSentences(1),
         "DESC_Appendix":  lorem.generateSentences(1),
        }
       ]
}
exports.get = DimProject

