const LoremIpsum = require("lorem-ipsum").LoremIpsum;

const lorem = new LoremIpsum({
    sentencesPerParagraph: {
      max: 8,
      min: 4
    },
    wordsPerSentence: {
      max: 16,
      min: 4
    }
  });

let DimTemplateProject = function() {
    return [
        {
         "DESC_GoalStatement":  lorem.generateSentences(1),
         "Parent_TemplateProject": 0, 
         "DESC_TemplateStatus": "Active Reporting", 
         "DESC_ProjectCategory": null, 
         "FL_ProjectLength": null, 
         "DESC_ProjectIntervention": null, 
         "FL_Access": null, 
         "DTTM_Insert": "2020-06-17 09.58.59.513", 
         "FL_Afford": null, 
         "DESC_TemplateStatusReason":  lorem.generateSentences(1),
         "DTTM_Update": null, 
         "ID_ProjectType": 4, 
         "DESC_ProjectTopic": null, 
         "DESC_ProjectName":  lorem.generateSentences(1),
         "DESC_ProjectType": "Labs", 
         "DESC_Appendix":  lorem.generateSentences(1),
         "ID_TemplateProject": 750, 
         "Dep_AcuteOrFacility": "Hospital", 
         "DESC_ProblemStatement":  lorem.generateSentences(1),
         "FL_Safety": null, 
         "DESC_ProjectStandard":  lorem.generateSentences(1),
         "MSAccess_ID_Template": null, 
         "ID_ProjectSetting": 2, 
         "FL_Quality": null
        }, 
        {
         "DESC_GoalStatement":  lorem.generateSentences(1),
         "Parent_TemplateProject": 0, 
         "DESC_TemplateStatus": "Active Reporting", 
         "DESC_ProjectCategory": null, 
         "FL_ProjectLength": null, 
         "DESC_ProjectIntervention": null, 
         "FL_Access": null, 
         "DTTM_Insert": "2020-06-17 14.09.52.293", 
         "FL_Afford": null, 
         "DESC_TemplateStatusReason":  lorem.generateSentences(1),
         "DTTM_Update": null, 
         "ID_ProjectType": 13, 
         "DESC_ProjectTopic": null, 
         "DESC_ProjectName":  lorem.generateSentences(1),
         "DESC_ProjectType": "Monitoring", 
         "DESC_Appendix":  lorem.generateSentences(1),
         "ID_TemplateProject": 751, 
         "Dep_AcuteOrFacility": "Ambulatory", 
         "DESC_ProblemStatement":  lorem.generateSentences(1),
         "FL_Safety": null, 
         "DESC_ProjectStandard":  lorem.generateSentences(1),
         "MSAccess_ID_Template": null, 
         "ID_ProjectSetting": 1, 
         "FL_Quality": null
        }, 
        {
         "DESC_GoalStatement":  lorem.generateSentences(1),
         "Parent_TemplateProject": 0, 
         "DESC_TemplateStatus": "Active Reporting", 
         "DESC_ProjectCategory": null, 
         "FL_ProjectLength": null, 
         "DESC_ProjectIntervention": null, 
         "FL_Access": null, 
         "DTTM_Insert": "2020-07-22 09.52.58.690", 
         "FL_Afford": null, 
         "DESC_TemplateStatusReason":  lorem.generateSentences(1),
         "DTTM_Update": null, 
         "ID_ProjectType": 10, 
         "DESC_ProjectTopic": null, 
         "DESC_ProjectName":  lorem.generateSentences(1),
         "DESC_ProjectType": "Visits", 
         "DESC_Appendix":  lorem.generateSentences(1),
         "ID_TemplateProject": 752, 
         "Dep_AcuteOrFacility": "Ambulatory", 
         "DESC_ProblemStatement":  lorem.generateSentences(1),
         "FL_Safety": null, 
         "DESC_ProjectStandard":  lorem.generateSentences(1),
         "MSAccess_ID_Template": null, 
         "ID_ProjectSetting": 1, 
         "FL_Quality": null
        }, 
        {
         "DESC_GoalStatement":  lorem.generateSentences(1),
         "Parent_TemplateProject": 0, 
         "DESC_TemplateStatus": "Active Reporting", 
         "DESC_ProjectCategory": null, 
         "FL_ProjectLength": null, 
         "DESC_ProjectIntervention": null, 
         "FL_Access": null, 
         "DTTM_Insert": "2020-07-22 09.56.40.757", 
         "FL_Afford": null, 
         "DESC_TemplateStatusReason":  lorem.generateSentences(1),
         "DTTM_Update": null, 
         "ID_ProjectType": 10, 
         "DESC_ProjectTopic": null, 
         "DESC_ProjectName":  lorem.generateSentences(1),
         "DESC_ProjectType": "Visits", 
         "DESC_Appendix":  lorem.generateSentences(1),
         "ID_TemplateProject": 753, 
         "Dep_AcuteOrFacility": "Ambulatory", 
         "DESC_ProblemStatement":  lorem.generateSentences(1),
         "FL_Safety": null, 
         "DESC_ProjectStandard":  lorem.generateSentences(1),
         "MSAccess_ID_Template": null, 
         "ID_ProjectSetting": 1, 
         "FL_Quality": null
        }, 
        {
         "DESC_GoalStatement":  lorem.generateSentences(1),
         "Parent_TemplateProject": 0, 
         "DESC_TemplateStatus": "Active Reporting", 
         "DESC_ProjectCategory": null, 
         "FL_ProjectLength": null, 
         "DESC_ProjectIntervention": null, 
         "FL_Access": null, 
         "DTTM_Insert": "2020-08-11 15.57.03.917", 
         "FL_Afford": null, 
         "DESC_TemplateStatusReason":  lorem.generateSentences(1),
         "DTTM_Update": null, 
         "ID_ProjectType": 6, 
         "DESC_ProjectTopic": null, 
         "DESC_ProjectName":  lorem.generateSentences(1),
         "DESC_ProjectType": "Pharmacy", 
         "DESC_Appendix":  lorem.generateSentences(1),
         "ID_TemplateProject": 754, 
         "Dep_AcuteOrFacility": "Ambulatory", 
         "DESC_ProblemStatement":  lorem.generateSentences(1),
         "FL_Safety": null, 
         "DESC_ProjectStandard":  lorem.generateSentences(1),
         "MSAccess_ID_Template": null, 
         "ID_ProjectSetting": 1, 
         "FL_Quality": null
        }, 
        {
         "DESC_GoalStatement":  lorem.generateSentences(1),
         "Parent_TemplateProject": 0, 
         "DESC_TemplateStatus": "Active Reporting", 
         "DESC_ProjectCategory": null, 
         "FL_ProjectLength": null, 
         "DESC_ProjectIntervention": null, 
         "FL_Access": null, 
         "DTTM_Insert": "2020-08-11 16.13.11.013", 
         "FL_Afford": null, 
         "DESC_TemplateStatusReason":  lorem.generateSentences(1),
         "DTTM_Update": null, 
         "ID_ProjectType": 6, 
         "DESC_ProjectTopic": null, 
         "DESC_ProjectName":  lorem.generateSentences(1),
         "DESC_ProjectType": "Pharmacy", 
         "DESC_Appendix":  lorem.generateSentences(1),
         "ID_TemplateProject": 755, 
         "Dep_AcuteOrFacility": "Ambulatory", 
         "DESC_ProblemStatement":  lorem.generateSentences(1),
         "FL_Safety": null, 
         "DESC_ProjectStandard":  lorem.generateSentences(1),
         "MSAccess_ID_Template": null, 
         "ID_ProjectSetting": 1, 
         "FL_Quality": null
        }, 
        {
         "DESC_GoalStatement":  lorem.generateSentences(1),
         "Parent_TemplateProject": 0, 
         "DESC_TemplateStatus": "Active Reporting", 
         "DESC_ProjectCategory": null, 
         "FL_ProjectLength": null, 
         "DESC_ProjectIntervention": null, 
         "FL_Access": null, 
         "DTTM_Insert": "2020-08-11 16.44.44.360", 
         "FL_Afford": null, 
         "DESC_TemplateStatusReason":  lorem.generateSentences(1),
         "DTTM_Update": null, 
         "ID_ProjectType": 6, 
         "DESC_ProjectTopic": null, 
         "DESC_ProjectName":  lorem.generateSentences(1),
         "DESC_ProjectType": "Pharmacy", 
         "DESC_Appendix":  lorem.generateSentences(1),
         "ID_TemplateProject": 756, 
         "Dep_AcuteOrFacility": "Ambulatory", 
         "DESC_ProblemStatement":  lorem.generateSentences(1),
         "FL_Safety": null, 
         "DESC_ProjectStandard":  lorem.generateSentences(1),
         "MSAccess_ID_Template": null, 
         "ID_ProjectSetting": 1, 
         "FL_Quality": null
        }, 
        {
         "DESC_GoalStatement":  lorem.generateSentences(1),
         "Parent_TemplateProject": 0, 
         "DESC_TemplateStatus": "Active Reporting", 
         "DESC_ProjectCategory": null, 
         "FL_ProjectLength": null, 
         "DESC_ProjectIntervention": null, 
         "FL_Access": null, 
         "DTTM_Insert": "2020-08-21 14.53.14.347", 
         "FL_Afford": null, 
         "DESC_TemplateStatusReason":  lorem.generateSentences(1),
         "DTTM_Update": null, 
         "ID_ProjectType": 6, 
         "DESC_ProjectTopic": null, 
         "DESC_ProjectName":  lorem.generateSentences(1),
         "DESC_ProjectType": "Pharmacy", 
         "DESC_Appendix":  lorem.generateSentences(1),
         "ID_TemplateProject": 757, 
         "Dep_AcuteOrFacility": "Hospital", 
         "DESC_ProblemStatement":  lorem.generateSentences(1),
         "FL_Safety": null, 
         "DESC_ProjectStandard":  lorem.generateSentences(1),
         "MSAccess_ID_Template": null, 
         "ID_ProjectSetting": 2, 
         "FL_Quality": null
        }, 
        {
         "DESC_GoalStatement":  lorem.generateSentences(1),
         "Parent_TemplateProject": 0, 
         "DESC_TemplateStatus": "Active Reporting", 
         "DESC_ProjectCategory": null, 
         "FL_ProjectLength": null, 
         "DESC_ProjectIntervention": null, 
         "FL_Access": null, 
         "DTTM_Insert": "2020-10-07 10.26.10.700", 
         "FL_Afford": null, 
         "DESC_TemplateStatusReason":  lorem.generateSentences(1),
         "DTTM_Update": null, 
         "ID_ProjectType": 6, 
         "DESC_ProjectTopic": null, 
         "DESC_ProjectName":  lorem.generateSentences(1),
         "DESC_ProjectType": "Pharmacy", 
         "DESC_Appendix":  lorem.generateSentences(1),
         "ID_TemplateProject": 758, 
         "Dep_AcuteOrFacility": "Ambulatory", 
         "DESC_ProblemStatement":  lorem.generateSentences(1),
         "FL_Safety": null, 
         "DESC_ProjectStandard":  lorem.generateSentences(1),
         "MSAccess_ID_Template": null, 
         "ID_ProjectSetting": 1, 
         "FL_Quality": null
        }, 
        {
         "DESC_GoalStatement":  lorem.generateSentences(1),
         "Parent_TemplateProject": 0, 
         "DESC_TemplateStatus": "Active Reporting", 
         "DESC_ProjectCategory": null, 
         "FL_ProjectLength": null, 
         "DESC_ProjectIntervention": null, 
         "FL_Access": null, 
         "DTTM_Insert": "2021-02-24 11.08.06.937", 
         "FL_Afford": null, 
         "DESC_TemplateStatusReason":  lorem.generateSentences(1),
         "DTTM_Update": null, 
         "ID_ProjectType": 4, 
         "DESC_ProjectTopic": null, 
         "DESC_ProjectName":  lorem.generateSentences(1),
         "DESC_ProjectType": "Labs", 
         "DESC_Appendix":  lorem.generateSentences(1),
         "ID_TemplateProject": 760, 
         "Dep_AcuteOrFacility": "Ambulatory", 
         "DESC_ProblemStatement":  lorem.generateSentences(1),
         "FL_Safety": null, 
         "DESC_ProjectStandard":  lorem.generateSentences(1),
         "MSAccess_ID_Template": null, 
         "ID_ProjectSetting": 1, 
         "FL_Quality": null
        }
       ]
}
exports.get = DimTemplateProject

