const LoremIpsum = require("lorem-ipsum").LoremIpsum;

const lorem = new LoremIpsum({
    sentencesPerParagraph: {
      max: 8,
      min: 4
    },
    wordsPerSentence: {
      max: 16,
      min: 4
    }
  });

let DimTemplateMeasure = function() {
    return [
        {
         "Dep_ProviderField":  lorem.generateWords(1),
         "FL_Balance": 0, 
         "Parent_TemplateProject": null, 
         "DESC_MeasureName":  lorem.generateSentences(1),
         "DESC_MeasureType": null, 
         "DESC_SummaryTable": "[" + lorem.generateWords(1) + "\\" + lorem.generateWords(1) + "].[" + lorem.generateWords(1) + "]",
         "DESC_DenominatorType":  lorem.generateSentences(1),
         "DESC_Exclusions":  lorem.generateSentences(1),
         "DESC_NumeratorType":  lorem.generateSentences(1),
         "DESC_ChangeDirection": "Up", 
         "FL_MonthLag": 0, 
         "FL_PatientExperience": 0, 
         "ID_TemplateMeasure": 1175, 
         "DESC_AvoidanceName": null, 
         "Dep_ProviderSource": "Epic Provider", 
         "Threshold": null, 
         "DESC_Subject": null, 
         "FL_ActiveMeasure": 1, 
         "Dep_Inclusion":  lorem.generateWords(1),
         "FL_Success": 1, 
         "ID_TemplateProject": 750, 
         "Dep_LocationField":  lorem.generateWords(1),
         "FL_Savings": 0, 
         "Parent_TemplateMeasure": 0, 
         "FL_DuplicateDenom": 0, 
         "FL_Duplicate_Numerator": 0, 
         "FL_StandardMeasure": 1, 
         "FL_Population": 0, 
         "FL_SpreadMeasure": 0, 
         "DESC_MetricType": "Percent"
        }, 
        {
         "Dep_ProviderField":  lorem.generateWords(1),
         "FL_Balance": 0, 
         "Parent_TemplateProject": null, 
         "DESC_MeasureName":  lorem.generateSentences(1),
         "DESC_MeasureType": null, 
         "DESC_SummaryTable": "[" + lorem.generateWords(1) + "\\" + lorem.generateWords(1) + "].[" + lorem.generateWords(1) + "]",
         "DESC_DenominatorType":  lorem.generateSentences(1),
         "DESC_Exclusions":  lorem.generateSentences(1),
         "DESC_NumeratorType":  lorem.generateSentences(1),
         "DESC_ChangeDirection": "Up", 
         "FL_MonthLag": 0, 
         "FL_PatientExperience": 0, 
         "ID_TemplateMeasure": 1176, 
         "DESC_AvoidanceName": null, 
         "Dep_ProviderSource": "Epic Provider", 
         "Threshold": 1, 
         "DESC_Subject": null, 
         "FL_ActiveMeasure": 1, 
         "Dep_Inclusion":  lorem.generateWords(1),
         "FL_Success": 0, 
         "ID_TemplateProject": 751, 
         "Dep_LocationField":  lorem.generateWords(1),
         "FL_Savings": 0, 
         "Parent_TemplateMeasure": 0, 
         "FL_DuplicateDenom": 0, 
         "FL_Duplicate_Numerator": 0, 
         "FL_StandardMeasure": 1, 
         "FL_Population": 0, 
         "FL_SpreadMeasure": 0, 
         "DESC_MetricType": "Percent"
        }, 
        {
         "Dep_ProviderField":  lorem.generateWords(1),
         "FL_Balance": 0, 
         "Parent_TemplateProject": null, 
         "DESC_MeasureName":  lorem.generateSentences(1),
         "DESC_MeasureType": null, 
         "DESC_SummaryTable": "[" + lorem.generateWords(1) + "\\" + lorem.generateWords(1) + "].[" + lorem.generateWords(1) + "]",
         "DESC_DenominatorType":  lorem.generateSentences(1),
         "DESC_Exclusions":  lorem.generateSentences(1),
         "DESC_NumeratorType":  lorem.generateSentences(1),
         "DESC_ChangeDirection": "Up", 
         "FL_MonthLag": 0, 
         "FL_PatientExperience": 0, 
         "ID_TemplateMeasure": 1177, 
         "DESC_AvoidanceName": null, 
         "Dep_ProviderSource": "Epic Provider", 
         "Threshold": 0.8, 
         "DESC_Subject": null, 
         "FL_ActiveMeasure": 1, 
         "Dep_Inclusion":  lorem.generateWords(1),
         "FL_Success": 1, 
         "ID_TemplateProject": 751, 
         "Dep_LocationField":  lorem.generateWords(1),
         "FL_Savings": 0, 
         "Parent_TemplateMeasure": 0, 
         "FL_DuplicateDenom": 0, 
         "FL_Duplicate_Numerator": 0, 
         "FL_StandardMeasure": 1, 
         "FL_Population": 0, 
         "FL_SpreadMeasure": 0, 
         "DESC_MetricType": "Percent"
        }, 
        {
         "Dep_ProviderField":  lorem.generateWords(1),
         "FL_Balance": 0, 
         "Parent_TemplateProject": null, 
         "DESC_MeasureName":  lorem.generateSentences(1),
         "DESC_MeasureType": null, 
         "DESC_SummaryTable": "[" + lorem.generateWords(1) + "\\" + lorem.generateWords(1) + "].[" + lorem.generateWords(1) + "]",
         "DESC_DenominatorType":  lorem.generateSentences(1),
         "DESC_Exclusions":  lorem.generateSentences(1),
         "DESC_NumeratorType":  lorem.generateSentences(1),
         "DESC_ChangeDirection": "Up", 
         "FL_MonthLag": 0, 
         "FL_PatientExperience": 0, 
         "ID_TemplateMeasure": 1179, 
         "DESC_AvoidanceName": null, 
         "Dep_ProviderSource": "Epic Provider", 
         "Threshold": null, 
         "DESC_Subject": null, 
         "FL_ActiveMeasure": 1, 
         "Dep_Inclusion":  lorem.generateWords(1),
         "FL_Success": 1, 
         "ID_TemplateProject": 752, 
         "Dep_LocationField":  lorem.generateWords(1),
         "FL_Savings": 0, 
         "Parent_TemplateMeasure": 0, 
         "FL_DuplicateDenom": 0, 
         "FL_Duplicate_Numerator": 0, 
         "FL_StandardMeasure": 1, 
         "FL_Population": 0, 
         "FL_SpreadMeasure": 0, 
         "DESC_MetricType": "Percent"
        }, 
        {
         "Dep_ProviderField":  lorem.generateWords(1),
         "FL_Balance": 0, 
         "Parent_TemplateProject": null, 
         "DESC_MeasureName":  lorem.generateSentences(1),
         "DESC_MeasureType": null, 
         "DESC_SummaryTable": "[" + lorem.generateWords(1) + "\\" + lorem.generateWords(1) + "].[" + lorem.generateWords(1) + "]",
         "DESC_DenominatorType":  lorem.generateSentences(1),
         "DESC_Exclusions":  lorem.generateSentences(1),
         "DESC_NumeratorType":  lorem.generateSentences(1),
         "DESC_ChangeDirection": "Up", 
         "FL_MonthLag": 0, 
         "FL_PatientExperience": 0, 
         "ID_TemplateMeasure": 1180, 
         "DESC_AvoidanceName": null, 
         "Dep_ProviderSource": "Epic Provider", 
         "Threshold": null, 
         "DESC_Subject": null, 
         "FL_ActiveMeasure": 1, 
         "Dep_Inclusion":  lorem.generateWords(1),
         "FL_Success": 1, 
         "ID_TemplateProject": 753, 
         "Dep_LocationField":  lorem.generateWords(1),
         "FL_Savings": 0, 
         "Parent_TemplateMeasure": 0, 
         "FL_DuplicateDenom": 0, 
         "FL_Duplicate_Numerator": 0, 
         "FL_StandardMeasure": 1, 
         "FL_Population": 0, 
         "FL_SpreadMeasure": 0, 
         "DESC_MetricType": "Percent"
        }, 
        {
         "Dep_ProviderField":  lorem.generateWords(1),
         "FL_Balance": 0, 
         "Parent_TemplateProject": null, 
         "DESC_MeasureName":  lorem.generateSentences(1),
         "DESC_MeasureType": null, 
         "DESC_SummaryTable": "[" + lorem.generateWords(1) + "\\" + lorem.generateWords(1) + "].[" + lorem.generateWords(1) + "]",
         "DESC_DenominatorType":  lorem.generateSentences(1),
         "DESC_Exclusions":  lorem.generateSentences(1),
         "DESC_NumeratorType":  lorem.generateSentences(1),
         "DESC_ChangeDirection": "Down", 
         "FL_MonthLag": 0, 
         "FL_PatientExperience": 0, 
         "ID_TemplateMeasure": 1181, 
         "DESC_AvoidanceName": null, 
         "Dep_ProviderSource": "Epic Provider", 
         "Threshold": null, 
         "DESC_Subject": null, 
         "FL_ActiveMeasure": 1, 
         "Dep_Inclusion":  lorem.generateWords(1),
         "FL_Success": 1, 
         "ID_TemplateProject": 754, 
         "Dep_LocationField":  lorem.generateWords(1),
         "FL_Savings": 0, 
         "Parent_TemplateMeasure": 0, 
         "FL_DuplicateDenom": 0, 
         "FL_Duplicate_Numerator": 0, 
         "FL_StandardMeasure": 1, 
         "FL_Population": 0, 
         "FL_SpreadMeasure": 0, 
         "DESC_MetricType": "Percent"
        }, 
        {
         "Dep_ProviderField":  lorem.generateWords(1),
         "FL_Balance": 0, 
         "Parent_TemplateProject": null, 
         "DESC_MeasureName":  lorem.generateSentences(1),
         "DESC_MeasureType": null, 
         "DESC_SummaryTable": "[" + lorem.generateWords(1) + "\\" + lorem.generateWords(1) + "].[" + lorem.generateWords(1) + "]",
         "DESC_DenominatorType":  lorem.generateSentences(1),
         "DESC_Exclusions":  lorem.generateSentences(1),
         "DESC_NumeratorType":  lorem.generateSentences(1),
         "DESC_ChangeDirection": "Down", 
         "FL_MonthLag": 0, 
         "FL_PatientExperience": 0, 
         "ID_TemplateMeasure": 1182, 
         "DESC_AvoidanceName": null, 
         "Dep_ProviderSource": "Epic Provider", 
         "Threshold": null, 
         "DESC_Subject": null, 
         "FL_ActiveMeasure": 1, 
         "Dep_Inclusion":  lorem.generateWords(1),
         "FL_Success": 0, 
         "ID_TemplateProject": 754, 
         "Dep_LocationField":  lorem.generateWords(1),
         "FL_Savings": 0, 
         "Parent_TemplateMeasure": 0, 
         "FL_DuplicateDenom": 0, 
         "FL_Duplicate_Numerator": 0, 
         "FL_StandardMeasure": 1, 
         "FL_Population": 0, 
         "FL_SpreadMeasure": 0, 
         "DESC_MetricType": "Unit"
        }, 
        {
         "Dep_ProviderField":  lorem.generateWords(1),
         "FL_Balance": 0, 
         "Parent_TemplateProject": null, 
         "DESC_MeasureName":  lorem.generateSentences(1),
         "DESC_MeasureType": null, 
         "DESC_SummaryTable": "[" + lorem.generateWords(1) + "\\" + lorem.generateWords(1) + "].[" + lorem.generateWords(1) + "]",
         "DESC_DenominatorType":  lorem.generateSentences(1),
         "DESC_Exclusions":  lorem.generateSentences(1),
         "DESC_NumeratorType":  lorem.generateSentences(1),
         "DESC_ChangeDirection": "Down", 
         "FL_MonthLag": 0, 
         "FL_PatientExperience": 0, 
         "ID_TemplateMeasure": 1183, 
         "DESC_AvoidanceName": null, 
         "Dep_ProviderSource": "Epic Provider", 
         "Threshold": null, 
         "DESC_Subject": null, 
         "FL_ActiveMeasure": 1, 
         "Dep_Inclusion":  lorem.generateWords(1),
         "FL_Success": 0, 
         "ID_TemplateProject": 754, 
         "Dep_LocationField":  lorem.generateWords(1),
         "FL_Savings": 0, 
         "Parent_TemplateMeasure": 0, 
         "FL_DuplicateDenom": 0, 
         "FL_Duplicate_Numerator": 0, 
         "FL_StandardMeasure": 1, 
         "FL_Population": 0, 
         "FL_SpreadMeasure": 0, 
         "DESC_MetricType": "Unit"
        }, 
        {
         "Dep_ProviderField":  lorem.generateWords(1),
         "FL_Balance": 0, 
         "Parent_TemplateProject": null, 
         "DESC_MeasureName":  lorem.generateSentences(1),
         "DESC_MeasureType": null, 
         "DESC_SummaryTable": "[" + lorem.generateWords(1) + "\\" + lorem.generateWords(1) + "].[" + lorem.generateWords(1) + "]",
         "DESC_DenominatorType":  lorem.generateSentences(1),
         "DESC_Exclusions":  lorem.generateSentences(1),
         "DESC_NumeratorType":  lorem.generateSentences(1),
         "DESC_ChangeDirection": "Down", 
         "FL_MonthLag": 0, 
         "FL_PatientExperience": 0, 
         "ID_TemplateMeasure": 1184, 
         "DESC_AvoidanceName": null, 
         "Dep_ProviderSource": "Epic Provider", 
         "Threshold": null, 
         "DESC_Subject": null, 
         "FL_ActiveMeasure": 1, 
         "Dep_Inclusion":  lorem.generateWords(1),
         "FL_Success": 0, 
         "ID_TemplateProject": 754, 
         "Dep_LocationField":  lorem.generateWords(1),
         "FL_Savings": 1, 
         "Parent_TemplateMeasure": 0, 
         "FL_DuplicateDenom": 0, 
         "FL_Duplicate_Numerator": 0, 
         "FL_StandardMeasure": 1, 
         "FL_Population": 0, 
         "FL_SpreadMeasure": 0, 
         "DESC_MetricType": "Cost"
        }, 
        {
         "Dep_ProviderField":  lorem.generateWords(1),
         "FL_Balance": 0, 
         "Parent_TemplateProject": null, 
         "DESC_MeasureName":  lorem.generateSentences(1),
         "DESC_MeasureType": null, 
         "DESC_SummaryTable": "[" + lorem.generateWords(1) + "\\" + lorem.generateWords(1) + "].[" + lorem.generateWords(1) + "]",
         "DESC_DenominatorType":  lorem.generateSentences(1),
         "DESC_Exclusions":  lorem.generateSentences(1),
         "DESC_NumeratorType":  lorem.generateSentences(1),
         "DESC_ChangeDirection": "Down", 
         "FL_MonthLag": 0, 
         "FL_PatientExperience": 0, 
         "ID_TemplateMeasure": 1185, 
         "DESC_AvoidanceName": null, 
         "Dep_ProviderSource": "Epic Provider", 
         "Threshold": null, 
         "DESC_Subject": null, 
         "FL_ActiveMeasure": 1, 
         "Dep_Inclusion":  lorem.generateWords(1),
         "FL_Success": 1, 
         "ID_TemplateProject": 755, 
         "Dep_LocationField":  lorem.generateWords(1),
         "FL_Savings": 0, 
         "Parent_TemplateMeasure": 0, 
         "FL_DuplicateDenom": 0, 
         "FL_Duplicate_Numerator": 0, 
         "FL_StandardMeasure": 1, 
         "FL_Population": 0, 
         "FL_SpreadMeasure": 0, 
         "DESC_MetricType": "Percent"
        }, 
        {
         "Dep_ProviderField":  lorem.generateWords(1),
         "FL_Balance": 0, 
         "Parent_TemplateProject": null, 
         "DESC_MeasureName":  lorem.generateSentences(1),
         "DESC_MeasureType": null, 
         "DESC_SummaryTable": "[" + lorem.generateWords(1) + "\\" + lorem.generateWords(1) + "].[" + lorem.generateWords(1) + "]",
         "DESC_DenominatorType":  lorem.generateSentences(1),
         "DESC_Exclusions":  lorem.generateSentences(1),
         "DESC_NumeratorType":  lorem.generateSentences(1),
         "DESC_ChangeDirection": "Down", 
         "FL_MonthLag": 0, 
         "FL_PatientExperience": 0, 
         "ID_TemplateMeasure": 1186, 
         "DESC_AvoidanceName": null, 
         "Dep_ProviderSource": "Epic Provider", 
         "Threshold": null, 
         "DESC_Subject": null, 
         "FL_ActiveMeasure": 1, 
         "Dep_Inclusion":  lorem.generateWords(1),
         "FL_Success": 0, 
         "ID_TemplateProject": 755, 
         "Dep_LocationField":  lorem.generateWords(1),
         "FL_Savings": 0, 
         "Parent_TemplateMeasure": 0, 
         "FL_DuplicateDenom": 0, 
         "FL_Duplicate_Numerator": 0, 
         "FL_StandardMeasure": 1, 
         "FL_Population": 0, 
         "FL_SpreadMeasure": 0, 
         "DESC_MetricType": "Unit"
        }, 
        {
         "Dep_ProviderField":  lorem.generateWords(1),
         "FL_Balance": 0, 
         "Parent_TemplateProject": null, 
         "DESC_MeasureName":  lorem.generateSentences(1),
         "DESC_MeasureType": null, 
         "DESC_SummaryTable": "[" + lorem.generateWords(1) + "\\" + lorem.generateWords(1) + "].[" + lorem.generateWords(1) + "]",
         "DESC_DenominatorType":  lorem.generateSentences(1),
         "DESC_Exclusions":  lorem.generateSentences(1),
         "DESC_NumeratorType":  lorem.generateSentences(1),
         "DESC_ChangeDirection": "Down", 
         "FL_MonthLag": 0, 
         "FL_PatientExperience": 0, 
         "ID_TemplateMeasure": 1187, 
         "DESC_AvoidanceName": null, 
         "Dep_ProviderSource": "Epic Provider", 
         "Threshold": null, 
         "DESC_Subject": null, 
         "FL_ActiveMeasure": 1, 
         "Dep_Inclusion":  lorem.generateWords(1),
         "FL_Success": 0, 
         "ID_TemplateProject": 755, 
         "Dep_LocationField":  lorem.generateWords(1),
         "FL_Savings": 0, 
         "Parent_TemplateMeasure": 0, 
         "FL_DuplicateDenom": 0, 
         "FL_Duplicate_Numerator": 0, 
         "FL_StandardMeasure": 1, 
         "FL_Population": 0, 
         "FL_SpreadMeasure": 0, 
         "DESC_MetricType": "Unit"
        }, 
        {
         "Dep_ProviderField":  lorem.generateWords(1),
         "FL_Balance": 0, 
         "Parent_TemplateProject": null, 
         "DESC_MeasureName":  lorem.generateSentences(1),
         "DESC_MeasureType": null, 
         "DESC_SummaryTable": "[" + lorem.generateWords(1) + "\\" + lorem.generateWords(1) + "].[" + lorem.generateWords(1) + "]",
         "DESC_DenominatorType":  lorem.generateSentences(1),
         "DESC_Exclusions":  lorem.generateSentences(1),
         "DESC_NumeratorType":  lorem.generateSentences(1),
         "DESC_ChangeDirection": "Down", 
         "FL_MonthLag": 0, 
         "FL_PatientExperience": 0, 
         "ID_TemplateMeasure": 1188, 
         "DESC_AvoidanceName": null, 
         "Dep_ProviderSource": "Epic Provider", 
         "Threshold": null, 
         "DESC_Subject": null, 
         "FL_ActiveMeasure": 1, 
         "Dep_Inclusion":  lorem.generateWords(1),
         "FL_Success": 0, 
         "ID_TemplateProject": 755, 
         "Dep_LocationField":  lorem.generateWords(1),
         "FL_Savings": 1, 
         "Parent_TemplateMeasure": 0, 
         "FL_DuplicateDenom": 0, 
         "FL_Duplicate_Numerator": 0, 
         "FL_StandardMeasure": 1, 
         "FL_Population": 0, 
         "FL_SpreadMeasure": 0, 
         "DESC_MetricType": "Cost"
        }, 
        {
         "Dep_ProviderField":  lorem.generateWords(1),
         "FL_Balance": 0, 
         "Parent_TemplateProject": null, 
         "DESC_MeasureName":  lorem.generateSentences(1),
         "DESC_MeasureType": null, 
         "DESC_SummaryTable": "[" + lorem.generateWords(1) + "\\" + lorem.generateWords(1) + "].[" + lorem.generateWords(1) + "]",
         "DESC_DenominatorType":  lorem.generateSentences(1),
         "DESC_Exclusions":  lorem.generateSentences(1),
         "DESC_NumeratorType":  lorem.generateSentences(1),
         "DESC_ChangeDirection": "Down", 
         "FL_MonthLag": 0, 
         "FL_PatientExperience": 0, 
         "ID_TemplateMeasure": 1192, 
         "DESC_AvoidanceName": null, 
         "Dep_ProviderSource": "Epic Provider", 
         "Threshold": null, 
         "DESC_Subject": null, 
         "FL_ActiveMeasure": 1, 
         "Dep_Inclusion":  lorem.generateWords(1),
         "FL_Success": 1, 
         "ID_TemplateProject": 756, 
         "Dep_LocationField":  lorem.generateWords(1),
         "FL_Savings": 0, 
         "Parent_TemplateMeasure": 0, 
         "FL_DuplicateDenom": 0, 
         "FL_Duplicate_Numerator": 0, 
         "FL_StandardMeasure": 1, 
         "FL_Population": 0, 
         "FL_SpreadMeasure": 0, 
         "DESC_MetricType": "Percent"
        }, 
        {
         "Dep_ProviderField":  lorem.generateWords(1),
         "FL_Balance": 0, 
         "Parent_TemplateProject": null, 
         "DESC_MeasureName":  lorem.generateSentences(1),
         "DESC_MeasureType": null, 
         "DESC_SummaryTable": "[" + lorem.generateWords(1) + "\\" + lorem.generateWords(1) + "].[" + lorem.generateWords(1) + "]",
         "DESC_DenominatorType":  lorem.generateSentences(1),
         "DESC_Exclusions":  lorem.generateSentences(1),
         "DESC_NumeratorType":  lorem.generateSentences(1),
         "DESC_ChangeDirection": "Down", 
         "FL_MonthLag": 0, 
         "FL_PatientExperience": 0, 
         "ID_TemplateMeasure": 1193, 
         "DESC_AvoidanceName": null, 
         "Dep_ProviderSource": "Epic Provider", 
         "Threshold": null, 
         "DESC_Subject": null, 
         "FL_ActiveMeasure": 1, 
         "Dep_Inclusion":  lorem.generateWords(1),
         "FL_Success": 0, 
         "ID_TemplateProject": 756, 
         "Dep_LocationField":  lorem.generateWords(1),
         "FL_Savings": 0, 
         "Parent_TemplateMeasure": 0, 
         "FL_DuplicateDenom": 0, 
         "FL_Duplicate_Numerator": 0, 
         "FL_StandardMeasure": 1, 
         "FL_Population": 0, 
         "FL_SpreadMeasure": 0, 
         "DESC_MetricType": "Unit"
        }, 
        {
         "Dep_ProviderField":  lorem.generateWords(1),
         "FL_Balance": 0, 
         "Parent_TemplateProject": null, 
         "DESC_MeasureName":  lorem.generateSentences(1),
         "DESC_MeasureType": null, 
         "DESC_SummaryTable": "[" + lorem.generateWords(1) + "\\" + lorem.generateWords(1) + "].[" + lorem.generateWords(1) + "]",
         "DESC_DenominatorType":  lorem.generateSentences(1),
         "DESC_Exclusions":  lorem.generateSentences(1),
         "DESC_NumeratorType":  lorem.generateSentences(1),
         "DESC_ChangeDirection": "Down", 
         "FL_MonthLag": 0, 
         "FL_PatientExperience": 0, 
         "ID_TemplateMeasure": 1194, 
         "DESC_AvoidanceName": null, 
         "Dep_ProviderSource": "Epic Provider", 
         "Threshold": null, 
         "DESC_Subject": null, 
         "FL_ActiveMeasure": 1, 
         "Dep_Inclusion":  lorem.generateWords(1),
         "FL_Success": 0, 
         "ID_TemplateProject": 756, 
         "Dep_LocationField":  lorem.generateWords(1),
         "FL_Savings": 0, 
         "Parent_TemplateMeasure": 0, 
         "FL_DuplicateDenom": 0, 
         "FL_Duplicate_Numerator": 0, 
         "FL_StandardMeasure": 1, 
         "FL_Population": 0, 
         "FL_SpreadMeasure": 0, 
         "DESC_MetricType": "Unit"
        }, 
        {
         "Dep_ProviderField":  lorem.generateWords(1),
         "FL_Balance": 0, 
         "Parent_TemplateProject": null, 
         "DESC_MeasureName":  lorem.generateSentences(1),
         "DESC_MeasureType": null, 
         "DESC_SummaryTable": "[" + lorem.generateWords(1) + "\\" + lorem.generateWords(1) + "].[" + lorem.generateWords(1) + "]",
         "DESC_DenominatorType":  lorem.generateSentences(1),
         "DESC_Exclusions":  lorem.generateSentences(1),
         "DESC_NumeratorType":  lorem.generateSentences(1),
         "DESC_ChangeDirection": "Down", 
         "FL_MonthLag": 0, 
         "FL_PatientExperience": 0, 
         "ID_TemplateMeasure": 1195, 
         "DESC_AvoidanceName": null, 
         "Dep_ProviderSource": "Epic Provider", 
         "Threshold": null, 
         "DESC_Subject": null, 
         "FL_ActiveMeasure": 1, 
         "Dep_Inclusion":  lorem.generateWords(1),
         "FL_Success": 0, 
         "ID_TemplateProject": 756, 
         "Dep_LocationField":  lorem.generateWords(1),
         "FL_Savings": 1, 
         "Parent_TemplateMeasure": 0, 
         "FL_DuplicateDenom": 0, 
         "FL_Duplicate_Numerator": 0, 
         "FL_StandardMeasure": 1, 
         "FL_Population": 0, 
         "FL_SpreadMeasure": 0, 
         "DESC_MetricType": "Cost"
        }, 
        {
         "Dep_ProviderField":  lorem.generateWords(1),
         "FL_Balance": 0, 
         "Parent_TemplateProject": null, 
         "DESC_MeasureName":  lorem.generateSentences(1),
         "DESC_MeasureType": null, 
         "DESC_SummaryTable": "[" + lorem.generateWords(1) + "\\" + lorem.generateWords(1) + "].[" + lorem.generateWords(1) + "]",
         "DESC_DenominatorType":  lorem.generateSentences(1),
         "DESC_Exclusions":  lorem.generateSentences(1),
         "DESC_NumeratorType":  lorem.generateSentences(1),
         "DESC_ChangeDirection": "Up", 
         "FL_MonthLag": 0, 
         "FL_PatientExperience": 0, 
         "ID_TemplateMeasure": 1196, 
         "DESC_AvoidanceName": null, 
         "Dep_ProviderSource": "Epic Provider", 
         "Threshold": null, 
         "DESC_Subject": null, 
         "FL_ActiveMeasure": 1, 
         "Dep_Inclusion":  lorem.generateWords(1),
         "FL_Success": 1, 
         "ID_TemplateProject": 757, 
         "Dep_LocationField":  lorem.generateWords(1),
         "FL_Savings": 0, 
         "Parent_TemplateMeasure": 0, 
         "FL_DuplicateDenom": 0, 
         "FL_Duplicate_Numerator": 0, 
         "FL_StandardMeasure": 1, 
         "FL_Population": 0, 
         "FL_SpreadMeasure": 0, 
         "DESC_MetricType": "Percent"
        }, 
        {
         "Dep_ProviderField":  lorem.generateWords(1),
         "FL_Balance": 0, 
         "Parent_TemplateProject": null, 
         "DESC_MeasureName":  lorem.generateSentences(1),
         "DESC_MeasureType": null, 
         "DESC_SummaryTable": "[" + lorem.generateWords(1) + "\\" + lorem.generateWords(1) + "].[" + lorem.generateWords(1) + "]",
         "DESC_DenominatorType":  lorem.generateSentences(1),
         "DESC_Exclusions":  lorem.generateSentences(1),
         "DESC_NumeratorType":  lorem.generateSentences(1),
         "DESC_ChangeDirection": "Up", 
         "FL_MonthLag": 0, 
         "FL_PatientExperience": 0, 
         "ID_TemplateMeasure": 1197, 
         "DESC_AvoidanceName": null, 
         "Dep_ProviderSource": "Epic Provider", 
         "Threshold": null, 
         "DESC_Subject": null, 
         "FL_ActiveMeasure": 1, 
         "Dep_Inclusion":  lorem.generateWords(1),
         "FL_Success": 1, 
         "ID_TemplateProject": 758, 
         "Dep_LocationField":  lorem.generateWords(1),
         "FL_Savings": 0, 
         "Parent_TemplateMeasure": 0, 
         "FL_DuplicateDenom": 1, 
         "FL_Duplicate_Numerator": 0, 
         "FL_StandardMeasure": 1, 
         "FL_Population": 0, 
         "FL_SpreadMeasure": 0, 
         "DESC_MetricType": "Percent"
        }, 
        {
         "Dep_ProviderField":  lorem.generateWords(1),
         "FL_Balance": 0, 
         "Parent_TemplateProject": null, 
         "DESC_MeasureName":  lorem.generateSentences(1),
         "DESC_MeasureType": null, 
         "DESC_SummaryTable": "[" + lorem.generateWords(1) + "\\" + lorem.generateWords(1) + "].[" + lorem.generateWords(1) + "]",
         "DESC_DenominatorType":  lorem.generateSentences(1),
         "DESC_Exclusions":  lorem.generateSentences(1),
         "DESC_NumeratorType":  lorem.generateSentences(1),
         "DESC_ChangeDirection": "Up", 
         "FL_MonthLag": 0, 
         "FL_PatientExperience": 0, 
         "ID_TemplateMeasure": 1198, 
         "DESC_AvoidanceName": null, 
         "Dep_ProviderSource": "Epic Provider", 
         "Threshold": null, 
         "DESC_Subject": null, 
         "FL_ActiveMeasure": 1, 
         "Dep_Inclusion":  lorem.generateWords(1),
         "FL_Success": 0, 
         "ID_TemplateProject": 758, 
         "Dep_LocationField":  lorem.generateWords(1),
         "FL_Savings": 0, 
         "Parent_TemplateMeasure": 0, 
         "FL_DuplicateDenom": 1, 
         "FL_Duplicate_Numerator": 0, 
         "FL_StandardMeasure": 1, 
         "FL_Population": 0, 
         "FL_SpreadMeasure": 0, 
         "DESC_MetricType": "Percent"
        }, 
        {
         "Dep_ProviderField":  lorem.generateWords(1),
         "FL_Balance": 0, 
         "Parent_TemplateProject": null, 
         "DESC_MeasureName":  lorem.generateSentences(1),
         "DESC_MeasureType": null, 
         "DESC_SummaryTable": "[" + lorem.generateWords(1) + "\\" + lorem.generateWords(1) + "].[" + lorem.generateWords(1) + "]",
         "DESC_DenominatorType":  lorem.generateSentences(1),
         "DESC_Exclusions":  lorem.generateSentences(1),
         "DESC_NumeratorType":  lorem.generateSentences(1),
         "DESC_ChangeDirection": "Up", 
         "FL_MonthLag": 0, 
         "FL_PatientExperience": 0, 
         "ID_TemplateMeasure": 1199, 
         "DESC_AvoidanceName": null, 
         "Dep_ProviderSource": "Epic Provider", 
         "Threshold": null, 
         "DESC_Subject": null, 
         "FL_ActiveMeasure": 1, 
         "Dep_Inclusion":  lorem.generateWords(1),
         "FL_Success": 0, 
         "ID_TemplateProject": 758, 
         "Dep_LocationField":  lorem.generateWords(1),
         "FL_Savings": 0, 
         "Parent_TemplateMeasure": 0, 
         "FL_DuplicateDenom": 1, 
         "FL_Duplicate_Numerator": 0, 
         "FL_StandardMeasure": 1, 
         "FL_Population": 0, 
         "FL_SpreadMeasure": 0, 
         "DESC_MetricType": "Percent"
        }, 
        {
         "Dep_ProviderField":  lorem.generateWords(1),
         "FL_Balance": 0, 
         "Parent_TemplateProject": null, 
         "DESC_MeasureName":  lorem.generateSentences(1),
         "DESC_MeasureType": null, 
         "DESC_SummaryTable": "[" + lorem.generateWords(1) + "\\" + lorem.generateWords(1) + "].[" + lorem.generateWords(1) + "]",
         "DESC_DenominatorType":  lorem.generateSentences(1),
         "DESC_Exclusions":  lorem.generateSentences(1),
         "DESC_NumeratorType":  lorem.generateSentences(1),
         "DESC_ChangeDirection": "Up", 
         "FL_MonthLag": 0, 
         "FL_PatientExperience": 0, 
         "ID_TemplateMeasure": 1203, 
         "DESC_AvoidanceName": null, 
         "Dep_ProviderSource": "Epic Provider", 
         "Threshold": null, 
         "DESC_Subject": null, 
         "FL_ActiveMeasure": 1, 
         "Dep_Inclusion":  lorem.generateWords(1),
         "FL_Success": 0, 
         "ID_TemplateProject": 758, 
         "Dep_LocationField":  lorem.generateWords(1),
         "FL_Savings": 0, 
         "Parent_TemplateMeasure": 0, 
         "FL_DuplicateDenom": 1, 
         "FL_Duplicate_Numerator": 0, 
         "FL_StandardMeasure": 1, 
         "FL_Population": 0, 
         "FL_SpreadMeasure": 0, 
         "DESC_MetricType": "Percent"
        }, 
        {
         "Dep_ProviderField":  lorem.generateWords(1),
         "FL_Balance": 0, 
         "Parent_TemplateProject": null, 
         "DESC_MeasureName":  lorem.generateSentences(1),
         "DESC_MeasureType": null, 
         "DESC_SummaryTable": "[" + lorem.generateWords(1) + "\\" + lorem.generateWords(1) + "].[" + lorem.generateWords(1) + "]",
         "DESC_DenominatorType":  lorem.generateSentences(1),
         "DESC_Exclusions":  lorem.generateSentences(1),
         "DESC_NumeratorType":  lorem.generateSentences(1),
         "DESC_ChangeDirection": "Up", 
         "FL_MonthLag": 0, 
         "FL_PatientExperience": 0, 
         "ID_TemplateMeasure": 1204, 
         "DESC_AvoidanceName": null, 
         "Dep_ProviderSource": "Epic Provider", 
         "Threshold": null, 
         "DESC_Subject": null, 
         "FL_ActiveMeasure": 1, 
         "Dep_Inclusion":  lorem.generateWords(1),
         "FL_Success": 0, 
         "ID_TemplateProject": 758, 
         "Dep_LocationField":  lorem.generateWords(1),
         "FL_Savings": 0, 
         "Parent_TemplateMeasure": 0, 
         "FL_DuplicateDenom": 1, 
         "FL_Duplicate_Numerator": 0, 
         "FL_StandardMeasure": 1, 
         "FL_Population": 0, 
         "FL_SpreadMeasure": 0, 
         "DESC_MetricType": "Percent"
        }, 
        {
         "Dep_ProviderField":  lorem.generateWords(1),
         "FL_Balance": 0, 
         "Parent_TemplateProject": null, 
         "DESC_MeasureName":  lorem.generateSentences(1),
         "DESC_MeasureType": null, 
         "DESC_SummaryTable": "[" + lorem.generateWords(1) + "\\" + lorem.generateWords(1) + "].[" + lorem.generateWords(1) + "]",
         "DESC_DenominatorType":  lorem.generateSentences(1),
         "DESC_Exclusions":  lorem.generateSentences(1),
         "DESC_NumeratorType":  lorem.generateSentences(1),
         "DESC_ChangeDirection": "Up", 
         "FL_MonthLag": 0, 
         "FL_PatientExperience": 0, 
         "ID_TemplateMeasure": 1205, 
         "DESC_AvoidanceName": null, 
         "Dep_ProviderSource": "Epic Provider", 
         "Threshold": null, 
         "DESC_Subject": null, 
         "FL_ActiveMeasure": 1, 
         "Dep_Inclusion":  lorem.generateWords(1),
         "FL_Success": 0, 
         "ID_TemplateProject": 758, 
         "Dep_LocationField":  lorem.generateWords(1),
         "FL_Savings": 0, 
         "Parent_TemplateMeasure": 0, 
         "FL_DuplicateDenom": 1, 
         "FL_Duplicate_Numerator": 0, 
         "FL_StandardMeasure": 1, 
         "FL_Population": 0, 
         "FL_SpreadMeasure": 0, 
         "DESC_MetricType": "Percent"
        }, 
        {
         "Dep_ProviderField":  lorem.generateWords(1),
         "FL_Balance": 0, 
         "Parent_TemplateProject": null, 
         "DESC_MeasureName":  lorem.generateSentences(1),
         "DESC_MeasureType": null, 
         "DESC_SummaryTable": "[" + lorem.generateWords(1) + "\\" + lorem.generateWords(1) + "].[" + lorem.generateWords(1) + "]",
         "DESC_DenominatorType":  lorem.generateSentences(1),
         "DESC_Exclusions":  lorem.generateSentences(1),
         "DESC_NumeratorType":  lorem.generateSentences(1),
         "DESC_ChangeDirection": "Down", 
         "FL_MonthLag": 0, 
         "FL_PatientExperience": 0, 
         "ID_TemplateMeasure": 1206, 
         "DESC_AvoidanceName": null, 
         "Dep_ProviderSource": "Epic Provider", 
         "Threshold": null, 
         "DESC_Subject": null, 
         "FL_ActiveMeasure": 1, 
         "Dep_Inclusion":  lorem.generateWords(1),
         "FL_Success": 1, 
         "ID_TemplateProject": 760, 
         "Dep_LocationField":  lorem.generateWords(1),
         "FL_Savings": 0, 
         "Parent_TemplateMeasure": 0, 
         "FL_DuplicateDenom": 0, 
         "FL_Duplicate_Numerator": 0, 
         "FL_StandardMeasure": 1, 
         "FL_Population": 0, 
         "FL_SpreadMeasure": 0, 
         "DESC_MetricType": "Percent"
        }, 
        {
         "Dep_ProviderField":  lorem.generateWords(1),
         "FL_Balance": 0, 
         "Parent_TemplateProject": null, 
         "DESC_MeasureName":  lorem.generateSentences(1),
         "DESC_MeasureType": null, 
         "DESC_SummaryTable": "[" + lorem.generateWords(1) + "\\" + lorem.generateWords(1) + "].[" + lorem.generateWords(1) + "]",
         "DESC_DenominatorType":  lorem.generateSentences(1),
         "DESC_Exclusions":  lorem.generateSentences(1),
         "DESC_NumeratorType":  lorem.generateSentences(1),
         "DESC_ChangeDirection": "Down", 
         "FL_MonthLag": 0, 
         "FL_PatientExperience": 0, 
         "ID_TemplateMeasure": 1207, 
         "DESC_AvoidanceName": null, 
         "Dep_ProviderSource": "Epic Provider", 
         "Threshold": null, 
         "DESC_Subject": null, 
         "FL_ActiveMeasure": 1, 
         "Dep_Inclusion":  lorem.generateWords(1),
         "FL_Success": 0, 
         "ID_TemplateProject": 760, 
         "Dep_LocationField":  lorem.generateWords(1),
         "FL_Savings": 1, 
         "Parent_TemplateMeasure": 0, 
         "FL_DuplicateDenom": 0, 
         "FL_Duplicate_Numerator": 0, 
         "FL_StandardMeasure": 1, 
         "FL_Population": 0, 
         "FL_SpreadMeasure": 0, 
         "DESC_MetricType": "Cost"
        }, 
        {
         "Dep_ProviderField":  lorem.generateWords(1),
         "FL_Balance": 0, 
         "Parent_TemplateProject": null, 
         "DESC_MeasureName":  lorem.generateSentences(1),
         "DESC_MeasureType": null, 
         "DESC_SummaryTable": "[" + lorem.generateWords(1) + "\\" + lorem.generateWords(1) + "].[" + lorem.generateWords(1) + "]",
         "DESC_DenominatorType":  lorem.generateSentences(1),
         "DESC_Exclusions":  lorem.generateSentences(1),
         "DESC_NumeratorType":  lorem.generateSentences(1),
         "DESC_ChangeDirection": "Down", 
         "FL_MonthLag": 0, 
         "FL_PatientExperience": 0, 
         "ID_TemplateMeasure": 1208, 
         "DESC_AvoidanceName": null, 
         "Dep_ProviderSource": "Epic Provider", 
         "Threshold": null, 
         "DESC_Subject": null, 
         "FL_ActiveMeasure": 1, 
         "Dep_Inclusion":  lorem.generateWords(1),
         "FL_Success": 0, 
         "ID_TemplateProject": 760, 
         "Dep_LocationField":  lorem.generateWords(1),
         "FL_Savings": 0, 
         "Parent_TemplateMeasure": 0, 
         "FL_DuplicateDenom": 0, 
         "FL_Duplicate_Numerator": 0, 
         "FL_StandardMeasure": 1, 
         "FL_Population": 0, 
         "FL_SpreadMeasure": 0, 
         "DESC_MetricType": "Percent"
        }, 
        {
         "Dep_ProviderField":  lorem.generateWords(1),
         "FL_Balance": 0, 
         "Parent_TemplateProject": null, 
         "DESC_MeasureName":  lorem.generateSentences(1),
         "DESC_MeasureType": null, 
         "DESC_SummaryTable": "[" + lorem.generateWords(1) + "\\" + lorem.generateWords(1) + "].[" + lorem.generateWords(1) + "]",
         "DESC_DenominatorType":  lorem.generateSentences(1),
         "DESC_Exclusions":  lorem.generateSentences(1),
         "DESC_NumeratorType":  lorem.generateSentences(1),
         "DESC_ChangeDirection": "Down", 
         "FL_MonthLag": 0, 
         "FL_PatientExperience": 0, 
         "ID_TemplateMeasure": 1209, 
         "DESC_AvoidanceName": null, 
         "Dep_ProviderSource": "Epic Provider", 
         "Threshold": null, 
         "DESC_Subject": null, 
         "FL_ActiveMeasure": 1, 
         "Dep_Inclusion":  lorem.generateWords(1),
         "FL_Success": 0, 
         "ID_TemplateProject": 760, 
         "Dep_LocationField":  lorem.generateWords(1),
         "FL_Savings": 0, 
         "Parent_TemplateMeasure": 0, 
         "FL_DuplicateDenom": 0, 
         "FL_Duplicate_Numerator": 0, 
         "FL_StandardMeasure": 1, 
         "FL_Population": 0, 
         "FL_SpreadMeasure": 0, 
         "DESC_MetricType": "Percent"
        }, 
        {
         "Dep_ProviderField":  lorem.generateWords(1),
         "FL_Balance": 0, 
         "Parent_TemplateProject": null, 
         "DESC_MeasureName":  lorem.generateSentences(1),
         "DESC_MeasureType": null, 
         "DESC_SummaryTable": "[" + lorem.generateWords(1) + "\\" + lorem.generateWords(1) + "].[" + lorem.generateWords(1) + "]",
         "DESC_DenominatorType":  lorem.generateSentences(1),
         "DESC_Exclusions":  lorem.generateSentences(1),
         "DESC_NumeratorType":  lorem.generateSentences(1),
         "DESC_ChangeDirection": "Down", 
         "FL_MonthLag": 0, 
         "FL_PatientExperience": 0, 
         "ID_TemplateMeasure": 1210, 
         "DESC_AvoidanceName": null, 
         "Dep_ProviderSource": "Epic Provider", 
         "Threshold": null, 
         "DESC_Subject": null, 
         "FL_ActiveMeasure": 1, 
         "Dep_Inclusion":  lorem.generateWords(1),
         "FL_Success": 0, 
         "ID_TemplateProject": 760, 
         "Dep_LocationField":  lorem.generateWords(1),
         "FL_Savings": 0, 
         "Parent_TemplateMeasure": 0, 
         "FL_DuplicateDenom": 0, 
         "FL_Duplicate_Numerator": 0, 
         "FL_StandardMeasure": 1, 
         "FL_Population": 0, 
         "FL_SpreadMeasure": 0, 
         "DESC_MetricType": "Percent"
        }, 
        {
         "Dep_ProviderField":  lorem.generateWords(1),
         "FL_Balance": 0, 
         "Parent_TemplateProject": null, 
         "DESC_MeasureName":  lorem.generateSentences(1),
         "DESC_MeasureType": null, 
         "DESC_SummaryTable": "[" + lorem.generateWords(1) + "\\" + lorem.generateWords(1) + "].[" + lorem.generateWords(1) + "]",
         "DESC_DenominatorType":  lorem.generateSentences(1),
         "DESC_Exclusions":  lorem.generateSentences(1),
         "DESC_NumeratorType":  lorem.generateSentences(1),
         "DESC_ChangeDirection": "Down", 
         "FL_MonthLag": 0, 
         "FL_PatientExperience": 0, 
         "ID_TemplateMeasure": 1211, 
         "DESC_AvoidanceName": null, 
         "Dep_ProviderSource": "Epic Provider", 
         "Threshold": null, 
         "DESC_Subject": null, 
         "FL_ActiveMeasure": 1, 
         "Dep_Inclusion":  lorem.generateWords(1),
         "FL_Success": 0, 
         "ID_TemplateProject": 760, 
         "Dep_LocationField":  lorem.generateWords(1),
         "FL_Savings": 0, 
         "Parent_TemplateMeasure": 0, 
         "FL_DuplicateDenom": 0, 
         "FL_Duplicate_Numerator": 0, 
         "FL_StandardMeasure": 1, 
         "FL_Population": 0, 
         "FL_SpreadMeasure": 0, 
         "DESC_MetricType": "Percent"
        }
       ]
}
exports.get = DimTemplateMeasure

